//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXCoreAutomatedsJobsJobMDL } from './Job.Model';

export namespace STXCoreAutomatedsJobsJobRLE
{

    @Injectable()
    export class JobRule extends STXCoreAutomatedsJobsJobMDL.JobRule
    {
    }
}
