//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;

namespace TFX.Core
{
    public class TFXCoreModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
        }
    }
}