//<auto-generated/>
import { XRule } from '../../material/Component/XComponent';
export namespace STXAppCoreINFMenuUserManuMDL
{

    export class UserManuRule extends XRule<UserManuDataSet>
    {
    }

    export class UserManuTuple extends XDataTuple
    {
        constructor(pSource?: any)
        {
            super();
            this.Assign(pSource);
        }

            override GetPKValue(): any { return this.CORxRecursoID.Value; }

        CORxRecursoID = new XDataField(XFieldState.Empty, () => 'XGuid', () => '');
        Titulo = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        Ordem = new XDataField(XFieldState.Empty, () => 'XInt32', () => '');
        Modulo = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        Icone = new XDataField(XFieldState.Empty, () => 'XString', () => '');

    }

    export class UserManuDataSet extends XDataSet<UserManuTuple>
    {
        constructor(pDataSet?: UserManuDataSet)
        {
            super();
            if (pDataSet != null)
                this.Assign(UserManuTuple, pDataSet);
            for (var i = 0; i < this.Tuples.length; i++)
            {
                let ttpl = this.Tuples[i];
                let stpl = pDataSet.Tuples[i];
            }
        }
    }

    export class UserManuRequest extends XRequest
    {
        CORxRecursoID?: string;
    }

    export class UserManuFilter extends XFilter
    {
        CORxRecursoID = new XDataField(XFieldState.Empty, () => 'XGuid', () => '');
    }
}
