//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFMenuUserManuMDL } from './UserManu.Model';

export namespace STXAppCoreINFMenuUserManuRLE
{

    @Injectable()
    export class UserManuRule extends STXAppCoreINFMenuUserManuMDL.UserManuRule
    {
    }
}
