//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  static class CORModel
    {

        public static class CORxDireiro
        {
            public const string sInserir = @"Inserir";
            public static Guid Inserir = new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8");
            public const string sInativar = @"Inativar";
            public static Guid Inativar = new Guid("DD926A04-2489-4BEF-BABA-87F63000B330");
            public const string sDeletar = @"Deletar";
            public static Guid Deletar = new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C");
            public const string sVisualizar = @"Visualizar";
            public static Guid Visualizar = new Guid("04B3A66C-C0F0-4F99-9864-08403BAA71BE");
            public const string sAlterar = @"Alterar";
            public static Guid Alterar = new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398");
        }

        public static class CORxEstado
        {
            public const string sInativo = @"Inativo";
            public const Int16 Inativo = (Int16)0;
            public const string sAtivo = @"Ativo";
            public const Int16 Ativo = (Int16)1;
            public const string sf_dfd_fdfd_ = @"f dfd fdfd ";
            public const Int16 f_dfd_fdfd_ = (Int16)2;
        }

        public static class CORxMenuItem
        {
            public const string sItem_da_POC = @"Item da POC";
            public static Guid Item_da_POC = new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C");
            public const string sNI = @"NI";
            public static Guid NI = new Guid("00000000-0000-0000-0000-000000000000");
            public const string sPOC = @"POC";
            public static Guid POC = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05");
        }
    }
}