//<auto-generated/>
using System;
using System.Linq;
using Microsoft.Extensions.DependencyInjection;

namespace STX.Core.Access
{
    public class STXCoreAccessModule
    {
        public const String sCID = "E07209C0-53D1-425C-AECF-11B8678E6A11";
        public static Guid gCID = new Guid(sCID);
    }
}