//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.App.Core.INF.DB
{
    public class CORxTenat : XEntity
    {
        public Boolean IsPKEmpty => Object.Equals(CORxTenatID, typeof(Guid).GetDefault());
        [Display(Name = "Tenat")]
        [Required()]
        public Guid? CORxTenatID {get; set;}

        public CORxPessoa CORxPessoa {get; set;}
    }
}
