//<auto-generated/>
using TFX.Core.Access.DB;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.App.Core.INF.DB
{
    public class TFXAppCoreINFContext : TFXCoreAccessContext
    {
        #region _CORxDireiro

        internal class _CORxDireiro
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxDireiro> _SeedData = new Dictionary<Guid, _CORxDireiro>()
                {
                    [new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8")] = new _CORxDireiro { CORxDireiroID = new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8"), Direito = @"Inserir" },
                    [new Guid("DD926A04-2489-4BEF-BABA-87F63000B330")] = new _CORxDireiro { CORxDireiroID = new Guid("DD926A04-2489-4BEF-BABA-87F63000B330"), Direito = @"Inativar" },
                    [new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C")] = new _CORxDireiro { CORxDireiroID = new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C"), Direito = @"Deletar" },
                    [new Guid("04B3A66C-C0F0-4F99-9864-08403BAA71BE")] = new _CORxDireiro { CORxDireiroID = new Guid("04B3A66C-C0F0-4F99-9864-08403BAA71BE"), Direito = @"Visualizar" },
                    [new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398")] = new _CORxDireiro { CORxDireiroID = new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398"), Direito = @"Alterar" }
                };
                public static _CORxDireiro[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxDireiroID, typeof(Guid).GetDefault());
            [Display(Name = "Direito")]
            [Required()]
            public Guid? CORxDireiroID {get; set;}
            [MaxLength(45)]
            [Required()]
            public String Direito {get; set;}
            public List<_CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<_CORxRecursoDireito>();
        }

        #endregion _CORxDireiro

        #region _CORxEstado

        internal class _CORxEstado
        {
            public class XDefault
            {
                private static Dictionary<Int16, _CORxEstado> _SeedData = new Dictionary<Int16, _CORxEstado>()
                {
                    [(Int16)0] = new _CORxEstado { CORxEstadoID = (Int16)0, Estado = @"Inativo" },
                    [(Int16)1] = new _CORxEstado { CORxEstadoID = (Int16)1, Estado = @"Ativo" }
                };
                public static _CORxEstado[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxEstadoID, typeof(Int16).GetDefault());
            [Display(Name = "Estado")]
            [Required()]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public Int16 CORxEstadoID {get; set;}
            [MaxLength(20)]
            [Required()]
            public String Estado {get; set;}
            public List<_CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<_CORxUsuarioPerfil>();
            public List<_CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<_CORxRecursoDireito>();
            public List<_CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<_CORxPerfilDireiro>();
        }

        #endregion _CORxEstado

        #region _CORxMenuItem

        internal class _CORxMenuItem
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxMenuItem> _SeedData = new Dictionary<Guid, _CORxMenuItem>()
                {
                    [new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C")] = new _CORxMenuItem { CORxMenuItemID = new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C"), Nome = @"Item da POC", CORxMenuItemPaiID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05"), Icone = @"bi bi-alipay" },
                    [new Guid("00000000-0000-0000-0000-000000000000")] = new _CORxMenuItem { CORxMenuItemID = new Guid("00000000-0000-0000-0000-000000000000"), Nome = @"NI", CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000"), Icone = @"NI" },
                    [new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05")] = new _CORxMenuItem { CORxMenuItemID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05"), Nome = @"POC", CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000"), Icone = @"bi bi-alipay" }
                };
                public static _CORxMenuItem[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxMenuItemID, typeof(Guid).GetDefault());
            [Display(Name = "Item de Menu")]
            [Required()]
            public Guid? CORxMenuItemID {get; set;}
            [Display(Name = "Item de Menu")]
            [Required()]
            public Guid CORxMenuItemPaiID {get; set;}
            [Display(Name = "Ícone")]
            [MaxLength(128)]
            [Required()]
            public String Icone {get; set;}
            [MaxLength(50)]
            [Required()]
            public String Nome {get; set;}
            public _CORxMenuItem ItemPai {get; set;}
            public List<_CORxRecurso> CORxRecurso {get; set;} = new List<_CORxRecurso>();
            public List<_CORxMenuItem> ItensFilhos {get; set;} = new List<_CORxMenuItem>();
        }

        #endregion _CORxMenuItem

        #region _CORxPerfil

        internal class _CORxPerfil
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxPerfil> _SeedData = new Dictionary<Guid, _CORxPerfil>()
                {
                    [new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1")] = new _CORxPerfil { CORxPerfilID = new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1"), Nome = @"Administrador" },
                    [new Guid("9A0B3913-4CA5-46D6-8161-3CFD80CA7AD2")] = new _CORxPerfil { CORxPerfilID = new Guid("9A0B3913-4CA5-46D6-8161-3CFD80CA7AD2"), Nome = @"Vendedor" },
                    [new Guid("00000000-0000-0000-0000-000000000000")] = new _CORxPerfil { CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000"), Nome = @"NA" }
                };
                public static _CORxPerfil[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxPerfilID, typeof(Guid).GetDefault());
            [Display(Name = "Perfil")]
            [Required()]
            public Guid? CORxPerfilID {get; set;}
            [Display(Name = "Nome do Perfil")]
            [MaxLength(45)]
            [Required()]
            public String Nome {get; set;}
            public List<_CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<_CORxUsuarioPerfil>();
            public List<_CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<_CORxPerfilDireiro>();
            public List<_CORxUsuario> CORxUsuario {get; set;} = new List<_CORxUsuario>();
        }

        #endregion _CORxPerfil

        #region _CORxPerfilDireiro

        internal class _CORxPerfilDireiro
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxPerfilDireiro> _SeedData = new Dictionary<Guid, _CORxPerfilDireiro>()
                {
                    [new Guid("3C1FC583-AE51-471D-B9E6-F32E1E4FED46")] = new _CORxPerfilDireiro { CORxPerfilDireiroID = new Guid("3C1FC583-AE51-471D-B9E6-F32E1E4FED46"), CORxPerfilID = new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1"), SYSxEstadoID = (Int16)1, CORxRecursoDireitoID = new Guid("BFFDEC08-20E6-473E-8E78-767FBC07498C") },
                    [new Guid("10853D40-58F1-4B93-874D-B49A61F8E486")] = new _CORxPerfilDireiro { CORxPerfilDireiroID = new Guid("10853D40-58F1-4B93-874D-B49A61F8E486"), CORxPerfilID = new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1"), SYSxEstadoID = (Int16)1, CORxRecursoDireitoID = new Guid("6187F500-B6AD-46E8-94E6-F2751C9358B1") },
                    [new Guid("726FF2AA-9CAA-46B9-9C1C-4422F23203B6")] = new _CORxPerfilDireiro { CORxPerfilDireiroID = new Guid("726FF2AA-9CAA-46B9-9C1C-4422F23203B6"), CORxPerfilID = new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1"), SYSxEstadoID = (Int16)1, CORxRecursoDireitoID = new Guid("789C7F93-9343-42FD-9970-E99BD4D03DE3") }
                };
                public static _CORxPerfilDireiro[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxPerfilDireiroID, typeof(Guid).GetDefault());
            [Display(Name = "Direitos por Perfil")]
            [Required()]
            public Guid? CORxPerfilDireiroID {get; set;}
            [Display(Name = "Perfil")]
            [Required()]
            public Guid CORxPerfilID {get; set;}
            [Display(Name = "Diureitos por Recurso")]
            [Required()]
            public Guid CORxRecursoDireitoID {get; set;}
            [Display(Name = "Estado")]
            [Required()]
            public Int16 SYSxEstadoID {get; set;}
            public _CORxPerfil CORxPerfil {get; set;}
            public _CORxEstado CORxEstado {get; set;}
            public _CORxRecursoDireito CORxRecursoDireito {get; set;}
        }

        #endregion _CORxPerfilDireiro

        #region _CORxPessoa

        internal class _CORxPessoa
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxPessoa> _SeedData = new Dictionary<Guid, _CORxPessoa>()
                {
                    [new Guid("8E330979-C053-45E6-A1ED-5FA20D03E18F")] = new _CORxPessoa { CORxPessoaID = new Guid("8E330979-C053-45E6-A1ED-5FA20D03E18F"), Nome = @"Administrador" },
                    [new Guid("00000000-0000-0000-0000-000000000000")] = new _CORxPessoa { CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000"), Nome = @"NA" }
                };
                public static _CORxPessoa[] SeedData => _SeedData.Values.ToArray();
            }
            public Boolean IsPKEmpty => Object.Equals(CORxPessoaID, typeof(Guid).GetDefault());
            [Display(Name = "Pessoa")]
            [Required()]
            public Guid? CORxPessoaID {get; set;}
            [MaxLength(256)]
            [Required()]
            public String Nome {get; set;}
            public List<_CORxUsuario> CORxUsuario {get; set;} = new List<_CORxUsuario>();
            public List<_CORxTenat> CORxTenat {get; set;} = new List<_CORxTenat>();
        }

        #endregion _CORxPessoa

        #region _CORxRecurso

        internal class _CORxRecurso
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxRecurso> _SeedData = new Dictionary<Guid, _CORxRecurso>()
                {
                    [new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0")] = new _CORxRecurso { CORxRecursoID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0"), Nome = @"Perfil de Acesso", CORxMenuItemID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05") },
                    [new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745")] = new _CORxRecurso { CORxRecursoID = new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745"), Nome = @"Usuário", CORxMenuItemID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05") }
                };
                public static _CORxRecurso[] SeedData => _SeedData.Values.ToArray();
            }
            [Display(Name = "Item de Menu")]
            [Required()]
            public Guid CORxMenuItemID {get; set;}
            public Boolean IsPKEmpty => Object.Equals(CORxRecursoID, typeof(Guid).GetDefault());
            [Display(Name = "Recurso")]
            [Required()]
            public Guid? CORxRecursoID {get; set;}
            [Display(Name = "Nome do Recuso")]
            [MaxLength(128)]
            [Required()]
            public String Nome {get; set;}
            public _CORxMenuItem CORxMenuItem {get; set;}
            public List<_CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<_CORxRecursoDireito>();
        }

        #endregion _CORxRecurso

        #region _CORxRecursoDireito

        internal class _CORxRecursoDireito
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxRecursoDireito> _SeedData = new Dictionary<Guid, _CORxRecursoDireito>()
                {
                    [new Guid("6187F500-B6AD-46E8-94E6-F2751C9358B1")] = new _CORxRecursoDireito { CORxRecursoDireitoID = new Guid("6187F500-B6AD-46E8-94E6-F2751C9358B1"), CORxDireiroID = new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8"), CORxRecursoID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0"), SYSxEstadoID = (Int16)1 },
                    [new Guid("BFFDEC08-20E6-473E-8E78-767FBC07498C")] = new _CORxRecursoDireito { CORxRecursoDireitoID = new Guid("BFFDEC08-20E6-473E-8E78-767FBC07498C"), CORxDireiroID = new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C"), CORxRecursoID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0"), SYSxEstadoID = (Int16)1 },
                    [new Guid("789C7F93-9343-42FD-9970-E99BD4D03DE3")] = new _CORxRecursoDireito { CORxRecursoDireitoID = new Guid("789C7F93-9343-42FD-9970-E99BD4D03DE3"), CORxDireiroID = new Guid("04B3A66C-C0F0-4F99-9864-08403BAA71BE"), CORxRecursoID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0"), SYSxEstadoID = (Int16)1 }
                };
                public static _CORxRecursoDireito[] SeedData => _SeedData.Values.ToArray();
            }
            [Display(Name = "Direito")]
            [Required()]
            public Guid CORxDireiroID {get; set;}
            public Boolean IsPKEmpty => Object.Equals(CORxRecursoDireitoID, typeof(Guid).GetDefault());
            [Display(Name = "Diureitos por Recurso")]
            [Required()]
            public Guid? CORxRecursoDireitoID {get; set;}
            [Display(Name = "Recurso")]
            [Required()]
            public Guid CORxRecursoID {get; set;}
            [Display(Name = "Estado")]
            [Required()]
            public Int16 SYSxEstadoID {get; set;}
            public _CORxDireiro CORxDireiro {get; set;}
            public _CORxRecurso CORxRecurso {get; set;}
            public _CORxEstado CORxEstado {get; set;}
            public List<_CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<_CORxPerfilDireiro>();
        }

        #endregion _CORxRecursoDireito

        #region _CORxTenat

        internal class _CORxTenat
        {
            public Boolean IsPKEmpty => Object.Equals(CORxTenatID, typeof(Guid).GetDefault());
            [Display(Name = "Tenat")]
            [Required()]
            public Guid? CORxTenatID {get; set;}
            public _CORxPessoa CORxPessoa {get; set;}
        }

        #endregion _CORxTenat

        #region _CORxUsuario

        internal class _CORxUsuario
        {
            public class XDefault
            {
                private static Dictionary<Guid, _CORxUsuario> _SeedData = new Dictionary<Guid, _CORxUsuario>()
                {
                    [new Guid("00000000-0000-0000-0000-000000000000")] = new _CORxUsuario { CORxUsuarioID = new Guid("00000000-0000-0000-0000-000000000000"), CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000"), CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000") },
                    [new Guid("EBA53C9E-C110-4CA3-96FD-420DC75207B1")] = new _CORxUsuario { CORxUsuarioID = new Guid("EBA53C9E-C110-4CA3-96FD-420DC75207B1"), CORxPessoaID = new Guid("8E330979-C053-45E6-A1ED-5FA20D03E18F"), CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000") }
                };
                public static _CORxUsuario[] SeedData => _SeedData.Values.ToArray();
            }
            [Display(Name = "Perfil")]
            [Required()]
            public Guid CORxPerfilID {get; set;}
            [Display(Name = "Pessoa")]
            [Required()]
            public Guid CORxPessoaID {get; set;}
            public Boolean IsPKEmpty => Object.Equals(CORxUsuarioID, typeof(Guid).GetDefault());
            [Display(Name = "Usuário")]
            [Required()]
            public Guid? CORxUsuarioID {get; set;}
            public _TAFxUsuario TAFxUsuario {get; set;}
            public _CORxPessoa CORxPessoa {get; set;}
            public _CORxPerfil CORxPerfil {get; set;}
            public List<_CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<_CORxUsuarioPerfil>();
        }

        #endregion _CORxUsuario

        #region _CORxUsuarioPerfil

        internal class _CORxUsuarioPerfil
        {
            [Display(Name = "Perfil")]
            [Required()]
            public Guid CORxPerfilID {get; set;}
            [Display(Name = "Usuário")]
            [Required()]
            public Guid CORxUsuarioID {get; set;}
            public Boolean IsPKEmpty => Object.Equals(CORxUsuarioPerfilID, typeof(Guid).GetDefault());
            [Display(Name = "Perfis por Uusário ")]
            [Required()]
            public Guid? CORxUsuarioPerfilID {get; set;}
            [Display(Name = "Estado")]
            [Required()]
            public Int16 SYSxEstadoID {get; set;}
            public _CORxUsuario CORxUsuario {get; set;}
            public _CORxPerfil CORxPerfil {get; set;}
            public _CORxEstado CORxEstado {get; set;}
        }

        #endregion _CORxUsuarioPerfil


        protected TFXAppCoreINFContext(DbContextOptions pOptions)
          : base(pOptions)
        {
        
        }

        public TFXAppCoreINFContext(DbContextOptions<TFXAppCoreINFContext> pOptions)
          : base(pOptions)
        {
        
        }

        internal DbSet<_CORxDireiro> CORxDireiro{get; set;}
        internal DbSet<_CORxEstado> CORxEstado{get; set;}
        internal DbSet<_CORxMenuItem> CORxMenuItem{get; set;}
        internal DbSet<_CORxPerfil> CORxPerfil{get; set;}
        internal DbSet<_CORxPerfilDireiro> CORxPerfilDireiro{get; set;}
        internal DbSet<_CORxPessoa> CORxPessoa{get; set;}
        internal DbSet<_CORxRecurso> CORxRecurso{get; set;}
        internal DbSet<_CORxRecursoDireito> CORxRecursoDireito{get; set;}
        internal DbSet<_CORxTenat> CORxTenat{get; set;}
        internal DbSet<_CORxUsuario> CORxUsuario{get; set;}
        internal DbSet<_CORxUsuarioPerfil> CORxUsuarioPerfil{get; set;}
        protected override void OnModelCreating(ModelBuilder pBuilder)
        {
        base.OnModelCreating(pBuilder);
            ConfigureCORxDireiro(pBuilder);
            ConfigureCORxEstado(pBuilder);
            ConfigureCORxMenuItem(pBuilder);
            ConfigureCORxPerfil(pBuilder);
            ConfigureCORxPerfilDireiro(pBuilder);
            ConfigureCORxPessoa(pBuilder);
            ConfigureCORxRecurso(pBuilder);
            ConfigureCORxRecursoDireito(pBuilder);
            ConfigureCORxTenat(pBuilder);
            ConfigureCORxUsuario(pBuilder);
            ConfigureCORxUsuarioPerfil(pBuilder);
        }

        private void ConfigureCORxDireiro(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxDireiro>(ett =>
            {
                ett.HasKey(e => e.CORxDireiroID).HasName("PK_CORxDireiro");
                
                ett.Property(d => d.CORxDireiroID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Direito).HasColumnType(GetDBType("String", 45));
                ett.ToTable("CORxDireiro");
                ett.HasData(_CORxDireiro.XDefault.SeedData);
            });
        }

        private void ConfigureCORxEstado(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxEstado>(ett =>
            {
                ett.HasKey(e => e.CORxEstadoID).HasName("PK_CORxEstado");
                
                ett.Property(d => d.CORxEstadoID).HasColumnType(GetDBType("Int16"));
                ett.Property(d => d.Estado).HasColumnType(GetDBType("String", 20));
                ett.ToTable("CORxEstado");
                ett.HasData(_CORxEstado.XDefault.SeedData);
            });
        }

        private void ConfigureCORxMenuItem(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxMenuItem>(ett =>
            {
                ett.HasKey(e => e.CORxMenuItemID).HasName("PK_CORxMenuItem");
                
                ett.Property(d => d.CORxMenuItemID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Nome).HasColumnType(GetDBType("String", 50));
                ett.Property(d => d.CORxMenuItemPaiID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Icone).HasColumnType(GetDBType("String", 128));
                ett.ToTable("CORxMenuItem");

                ett.HasOne(d => d.ItemPai)
                   .WithMany(p => p.ItensFilhos)
                   .HasForeignKey(d => d.CORxMenuItemPaiID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_089E501462F24B4CB82B6401E77C1CD9");

                ett.HasIndex(d => d.CORxMenuItemPaiID).HasDatabaseName("IX_089E501462F24B4CB82B6401E77C1CD9");
                ett.HasData(_CORxMenuItem.XDefault.SeedData);
            });
        }

        private void ConfigureCORxPerfil(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxPerfil>(ett =>
            {
                ett.HasKey(e => e.CORxPerfilID).HasName("PK_CORxPerfil");
                
                ett.Property(d => d.CORxPerfilID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Nome).HasColumnType(GetDBType("String", 45));
                ett.ToTable("CORxPerfil");
                ett.HasData(_CORxPerfil.XDefault.SeedData);
            });
        }

        private void ConfigureCORxPerfilDireiro(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxPerfilDireiro>(ett =>
            {
                ett.HasKey(e => e.CORxPerfilDireiroID).HasName("PK_CORxPerfilDireiro");
                
                ett.Property(d => d.CORxPerfilDireiroID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxPerfilID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.SYSxEstadoID).HasColumnType(GetDBType("Int16"));
                ett.Property(d => d.CORxRecursoDireitoID).HasColumnType(GetDBType("Guid"));
                ett.ToTable("CORxPerfilDireiro");

                ett.HasOne(d => d.CORxPerfil)
                   .WithMany(p => p.CORxPerfilDireiro)
                   .HasForeignKey(d => d.CORxPerfilID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_DB2EF4796E004A85B4BBEC4BAFB60B61");

                ett.HasOne(d => d.CORxRecursoDireito)
                   .WithMany(p => p.CORxPerfilDireiro)
                   .HasForeignKey(d => d.CORxRecursoDireitoID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_43FA8B4D965A44388AB05C4C95CD4120");

                ett.HasOne(d => d.CORxEstado)
                   .WithMany(p => p.CORxPerfilDireiro)
                   .HasForeignKey(d => d.SYSxEstadoID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_C81CBAAB358F4F87B64A7EFD7808B76B");

                ett.HasIndex(d => d.CORxPerfilID).HasDatabaseName("IX_DB2EF4796E004A85B4BBEC4BAFB60B61");
                ett.HasIndex(d => d.SYSxEstadoID).HasDatabaseName("IX_C81CBAAB358F4F87B64A7EFD7808B76B");
                ett.HasIndex(d => d.CORxRecursoDireitoID).HasDatabaseName("IX_43FA8B4D965A44388AB05C4C95CD4120");

                ett.HasIndex(e => new { e.CORxPerfilID, e.CORxPerfilDireiroID })
                    .IsUnique()
                    .HasDatabaseName("IX_8EA98120_28B4_458C_946B_E9B0000C518D");
                ett.HasData(_CORxPerfilDireiro.XDefault.SeedData);
            });
        }

        private void ConfigureCORxPessoa(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxPessoa>(ett =>
            {
                ett.HasKey(e => e.CORxPessoaID).HasName("PK_CORxPessoa");
                
                ett.Property(d => d.CORxPessoaID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Nome).HasColumnType(GetDBType("String", 256));
                ett.ToTable("CORxPessoa");
                ett.HasData(_CORxPessoa.XDefault.SeedData);
            });
        }

        private void ConfigureCORxRecurso(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxRecurso>(ett =>
            {
                ett.HasKey(e => e.CORxRecursoID).HasName("PK_CORxRecurso");
                
                ett.Property(d => d.CORxRecursoID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.Nome).HasColumnType(GetDBType("String", 128));
                ett.Property(d => d.CORxMenuItemID).HasColumnType(GetDBType("Guid"));
                ett.ToTable("CORxRecurso");

                ett.HasOne(d => d.CORxMenuItem)
                   .WithMany(p => p.CORxRecurso)
                   .HasForeignKey(d => d.CORxMenuItemID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_DD2B2F889A7341ACB8763984D8EB927F");

                ett.HasIndex(d => d.CORxMenuItemID).HasDatabaseName("IX_DD2B2F889A7341ACB8763984D8EB927F");
                ett.HasData(_CORxRecurso.XDefault.SeedData);
            });
        }

        private void ConfigureCORxRecursoDireito(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxRecursoDireito>(ett =>
            {
                ett.HasKey(e => e.CORxRecursoDireitoID).HasName("PK_CORxRecursoDireito");
                
                ett.Property(d => d.CORxRecursoDireitoID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxDireiroID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxRecursoID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.SYSxEstadoID).HasColumnType(GetDBType("Int16"));
                ett.ToTable("CORxRecursoDireito");

                ett.HasOne(d => d.CORxDireiro)
                   .WithMany(p => p.CORxRecursoDireito)
                   .HasForeignKey(d => d.CORxDireiroID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_FEBE37E773C04510917C09AA991BA695");

                ett.HasOne(d => d.CORxEstado)
                   .WithMany(p => p.CORxRecursoDireito)
                   .HasForeignKey(d => d.SYSxEstadoID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_662808A15CC541869E041EB76DBF81F2");

                ett.HasOne(d => d.CORxRecurso)
                   .WithMany(p => p.CORxRecursoDireito)
                   .HasForeignKey(d => d.CORxRecursoID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_63A2BC55DE5B48F9B50DB67210086133");

                ett.HasIndex(d => d.CORxDireiroID).HasDatabaseName("IX_FEBE37E773C04510917C09AA991BA695");
                ett.HasIndex(d => d.CORxRecursoID).HasDatabaseName("IX_63A2BC55DE5B48F9B50DB67210086133");
                ett.HasIndex(d => d.SYSxEstadoID).HasDatabaseName("IX_662808A15CC541869E041EB76DBF81F2");

                ett.HasIndex(e => new { e.CORxDireiroID, e.CORxRecursoID })
                    .IsUnique()
                    .HasDatabaseName("IX_29FB7252_4D26_4B87_85F7_DED1FB18AC29");
                ett.HasData(_CORxRecursoDireito.XDefault.SeedData);
            });
        }

        private void ConfigureCORxTenat(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxTenat>(ett =>
            {
                ett.HasKey(e => e.CORxTenatID).HasName("PK_CORxTenat");
                
                ett.Property(d => d.CORxTenatID).HasColumnType(GetDBType("Guid"));
                ett.ToTable("CORxTenat");

                ett.HasOne(d => d.CORxPessoa)
                   .WithMany()
                   .HasForeignKey(d => d.CORxTenatID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_7763556284A541589093B4B776F38198");

                ett.HasIndex(d => d.CORxTenatID).HasDatabaseName("IX_7763556284A541589093B4B776F38198");
            });
        }

        private void ConfigureCORxUsuario(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxUsuario>(ett =>
            {
                ett.HasKey(e => e.CORxUsuarioID).HasName("PK_CORxUsuario");
                
                ett.Property(d => d.CORxUsuarioID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxPessoaID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxPerfilID).HasColumnType(GetDBType("Guid"));
                ett.ToTable("CORxUsuario");

                ett.HasOne(d => d.CORxPerfil)
                   .WithMany(p => p.CORxUsuario)
                   .HasForeignKey(d => d.CORxPerfilID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_5EADF4BC787543D68D639FEBDDD377A1");

                ett.HasOne(d => d.TAFxUsuario)
                   .WithMany()
                   .HasForeignKey(d => d.CORxUsuarioID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_74C786F513D84B83B262F901573BCE27");

                ett.HasOne(d => d.CORxPessoa)
                   .WithMany(p => p.CORxUsuario)
                   .HasForeignKey(d => d.CORxPessoaID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_C9471B8665C04206AC2FBA967434C37A");

                ett.HasIndex(d => d.CORxUsuarioID).HasDatabaseName("IX_74C786F513D84B83B262F901573BCE27");
                ett.HasIndex(d => d.CORxPessoaID).HasDatabaseName("IX_C9471B8665C04206AC2FBA967434C37A");
                ett.HasIndex(d => d.CORxPerfilID).HasDatabaseName("IX_5EADF4BC787543D68D639FEBDDD377A1");
                ett.HasData(_CORxUsuario.XDefault.SeedData);
            });
        }

        private void ConfigureCORxUsuarioPerfil(ModelBuilder pBuilder)
        {
            pBuilder.Entity<_CORxUsuarioPerfil>(ett =>
            {
                ett.HasKey(e => e.CORxUsuarioPerfilID).HasName("PK_CORxUsuarioPerfil");
                
                ett.Property(d => d.CORxUsuarioPerfilID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxUsuarioID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.CORxPerfilID).HasColumnType(GetDBType("Guid"));
                ett.Property(d => d.SYSxEstadoID).HasColumnType(GetDBType("Int16"));
                ett.ToTable("CORxUsuarioPerfil");

                ett.HasOne(d => d.CORxPerfil)
                   .WithMany(p => p.CORxUsuarioPerfil)
                   .HasForeignKey(d => d.CORxPerfilID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_A1545961E23B49F9A6C3797816459BA6");

                ett.HasOne(d => d.CORxUsuario)
                   .WithMany(p => p.CORxUsuarioPerfil)
                   .HasForeignKey(d => d.CORxUsuarioID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_277FC3C02F294E4BB98861248A39AF3E");

                ett.HasOne(d => d.CORxEstado)
                   .WithMany(p => p.CORxUsuarioPerfil)
                   .HasForeignKey(d => d.SYSxEstadoID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_DF6B83584AFE4750963FA1CCDD988B7A");

                ett.HasIndex(d => d.CORxUsuarioID).HasDatabaseName("IX_277FC3C02F294E4BB98861248A39AF3E");
                ett.HasIndex(d => d.CORxPerfilID).HasDatabaseName("IX_A1545961E23B49F9A6C3797816459BA6");
                ett.HasIndex(d => d.SYSxEstadoID).HasDatabaseName("IX_DF6B83584AFE4750963FA1CCDD988B7A");

                ett.HasIndex(e => new { e.CORxUsuarioID, e.CORxPerfilID })
                    .IsUnique()
                    .HasDatabaseName("IX_41898A44_44C6_4757_BCD7_45183345E9D3");
            });
        }
    }
}
