//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public class CORxPerfil
    {
        public class XDefault
        {
            private static Dictionary<Guid, CORxPerfil> _SeedData = new Dictionary<Guid, CORxPerfil>()
            {
                [new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1")] = new CORxPerfil { CORxPerfilID = new Guid("67BD4F5D-4FB2-40A0-84C1-BD75AE669DD1"), Nome = @"Administrador" },
                [new Guid("9A0B3913-4CA5-46D6-8161-3CFD80CA7AD2")] = new CORxPerfil { CORxPerfilID = new Guid("9A0B3913-4CA5-46D6-8161-3CFD80CA7AD2"), Nome = @"Vendedor" }
            };

            public static CORxPerfil[] SeedData => _SeedData.Values.ToArray();

        }
        [Display(Name = "Perfil")]
        [Required()]
        public Guid CORxPerfilID {get; set;}

        [Display(Name = "Nome do Perfil")]
        [MaxLength(45)]
        [Required()]
        public String Nome {get; set;}

        public List<CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<CORxUsuarioPerfil>();
        public List<CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<CORxPerfilDireiro>();
    }
}
