//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.App.Core.INF.DB
{
    public class CORxUsuarioPerfil : XEntity
    {
        [Display(Name = "Perfil")]
        [Required()]
        public Guid CORxPerfilID {get; set;}

        [Display(Name = "Usuário")]
        [Required()]
        public Guid CORxUsuarioID {get; set;}

        public Boolean IsPKEmpty => Object.Equals(CORxUsuarioPerfilID, typeof(Guid).GetDefault());
        [Display(Name = "Perfis por Uusário ")]
        [Required()]
        public Guid? CORxUsuarioPerfilID {get; set;}

        [Display(Name = "Estado")]
        [Required()]
        public Int16 SYSxEstadoID {get; set;}

        public CORxUsuario CORxUsuario {get; set;}
        public CORxPerfil CORxPerfil {get; set;}
        public CORxEstado CORxEstado {get; set;}
    }
}
