//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public class CORxEstado
    {
        public class XDefault
        {
            private static Dictionary<Int16, CORxEstado> _SeedData = new Dictionary<Int16, CORxEstado>()
            {
                [(Int16)0] = new CORxEstado { CORxEstadoID = (Int16)0, Estado = @"Inativo" },
                [(Int16)1] = new CORxEstado { CORxEstadoID = (Int16)1, Estado = @"Ativo" }
            };

            public static CORxEstado[] SeedData => _SeedData.Values.ToArray();

        }
        [Display(Name = "Estado")]
        [Required()]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Int16 CORxEstadoID {get; set;}

        [MaxLength(20)]
        [Required()]
        public String Estado {get; set;}

        public List<CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<CORxUsuarioPerfil>();
        public List<CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<CORxRecursoDireito>();
        public List<CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<CORxPerfilDireiro>();
    }
}
