//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  partial class CORxPessoaFisica
    {
        [Display(Name = "Pessoa Física")]
        [Required()]
        public Guid? CORxPessoaFisicaID {get; set;} = Guid.Empty;

        [Display(Name = "Usuário")]
        [Required()]
        public Guid CORxUsuarioID {get; set;}

        [Display(Name = "Endereco")]
        [MaxLength(150)]
        [Required()]
        public String Enderecos {get; set;}

        [MaxLength(150)]
        public String Nome {get; set;}

        public CORxUsuario CORxUsuario {get; set;}
    }
}
