//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public class CORxPerfil
    {
        [Display(Name = "Perfil")]
        [Required()]
        public Guid? CORxPerfilID {get; set;} = Guid.Empty;

        [Display(Name = "Nome do Perfil")]
        [MaxLength(45)]
        [Required()]
        public String Nome {get; set;}

        public List<CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<CORxUsuarioPerfil>();
        public List<CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<CORxPerfilDireiro>();
    }
}
