//<auto-generated/>
using STX.Core.Access.DB;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using STX.Core;

namespace STX.App.Core.INF.DB
{
    public class STXAppCoreINFContext : STXCoreAccessContext
    {

        public STXAppCoreINFContext(DbContextOptions pOptions)
          : base(pOptions)
        {
        
        }

        public STXAppCoreINFContext(DbContextOptions<STXAppCoreINFContext> pOptions)
          : base(pOptions)
        {
        
        }

        public DbSet<CORxUsuario> CORxUsuario{get; set;}
        protected override void OnModelCreating(ModelBuilder pBuilder)
        {
            ConfigureCORxUsuario(pBuilder);
        }

        private void ConfigureCORxUsuario(ModelBuilder pBuilder)
        {
            pBuilder.Entity<CORxUsuario>(ett =>
            {
                ett.HasKey(e => e.CORxUsuarioID).HasName("PK_CORxUsuario");
                
                ett.Property(d => d.CORxUsuarioID).HasColumnType(GetDBType("Guid", 0, 0));
                ett.ToTable("CORxUsuario");

                ett.HasOne<TAFxUsuario>()
                   .WithMany()
                   .HasForeignKey(d => d.CORxUsuarioID)
                   .OnDelete(DeleteBehavior.Restrict)
                   .HasConstraintName("FK_74C786F513D84B83B262F901573BCE27");

                ett.HasIndex(d => d.CORxUsuarioID).HasDatabaseName("IX_74C786F513D84B83B262F901573BCE27");
            });
        }
    }
}