//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public class CORxUsuarioPerfil
    {
        [Display(Name = "Perfil")]
        [Required()]
        public Guid CORxPerfilID {get; set;}

        [Display(Name = "Usuário")]
        [Required()]
        public Guid CORxUsuarioID {get; set;}

        [Display(Name = "Perfis por Uusário ")]
        [Required()]
        public Guid? CORxUsuarioPerfilID {get; set;} = Guid.Empty;

        [Display(Name = "Estado")]
        [Required()]
        public Int16 SYSxEstadoID {get; set;}

        public CORxUsuario CORxUsuario {get; set;}
        public CORxPerfil CORxPerfil {get; set;}
        public CORxEstado CORxEstado {get; set;}
    }
}
