//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  partial class CORxPerfilDireiro
    {
        [Display(Name = "Direito")]
        [Required()]
        public Guid CORxDireiroID {get; set;}

        [Display(Name = "Direitos por Perfil")]
        [Required()]
        public Guid? CORxPerfilDireiroID {get; set;} = Guid.Empty;

        [Display(Name = "Perfil")]
        [Required()]
        public Guid CORxPerfilID {get; set;}

        [Display(Name = "Estado")]
        [Required()]
        public Int16 SYSxEstadoID {get; set;}

        public CORxDireiro CORxDireiro {get; set;}
        public CORxPerfil CORxPerfil {get; set;}
        public CORxEstado CORxEstado {get; set;}
    }
}
