//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  partial class CORxMenuItem
    {
        #region XDefault

        public class XDefault
        {
            public static Guid _620DF346CC9D4333B57E8B5454E5617C = new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C");
            public static Guid _00000000000000000000000000000000 = new Guid("00000000-0000-0000-0000-000000000000");
            public static Guid _2DE8C87D4E4A4E57A567A6F5ACB92E05 = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05");
            private static Dictionary<Guid, CORxMenuItem> _SeedData = new Dictionary<Guid, CORxMenuItem>()
            {
                [new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C")] = new CORxMenuItem { CORxMenuItemID = new Guid("620DF346-CC9D-4333-B57E-8B5454E5617C"), Nome = @"Item da POC", CORxMenuItemPaiID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05") },
                [new Guid("00000000-0000-0000-0000-000000000000")] = new CORxMenuItem { CORxMenuItemID = new Guid("00000000-0000-0000-0000-000000000000"), Nome = null, CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000") },
                [new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05")] = new CORxMenuItem { CORxMenuItemID = new Guid("2DE8C87D-4E4A-4E57-A567-A6F5ACB92E05"), Nome = @"POC", CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000") }
            };

            public static CORxMenuItem[] SeedData => _SeedData.Values.ToArray();

        }
        #endregion XDefault
        [Display(Name = "Item de Menu")]
        [Required()]
        public Guid? CORxMenuItemID {get; set;} = Guid.Empty;

        [Display(Name = "Item de Menu")]
        [Required()]
        public Guid CORxMenuItemPaiID {get; set;}

        [MaxLength(50)]
        [Required()]
        public String Nome {get; set;}

        public CORxMenuItem CORxMenuItem {get; set;}
        public List<CORxRecurso> CORxRecurso {get; set;} = new List<CORxRecurso>();
        public List<CORxMenuItem> CORxMenuItem {get; set;} = new List<CORxMenuItem>();
    }
}
