//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  partial class CORxEstado
    {
        #region XDefault

        public class XDefault
        {
            public const Int16 _0 = (Int16)0;
            public const Int16 _1 = (Int16)1;
            private static Dictionary<Int16, CORxEstado> _SeedData = new Dictionary<Int16, CORxEstado>()
            {
                [(Int16)0] = new CORxEstado { CORxEstadoID = (Int16)0, Estado = @"Inativo" },
                [(Int16)1] = new CORxEstado { CORxEstadoID = (Int16)1, Estado = @"Ativo" }
            };

            public static CORxEstado[] SeedData => _SeedData.Values.ToArray();

        }
        #endregion XDefault
        [Display(Name = "Estado")]
        [Required()]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Int16 CORxEstadoID {get; set;}

        [MaxLength(20)]
        [Required()]
        public String Estado {get; set;}

        public List<CORxUsuarioPerfil> CORxUsuarioPerfil {get; set;} = new List<CORxUsuarioPerfil>();
        public List<CORxDireiro> CORxDireiro {get; set;} = new List<CORxDireiro>();
        public List<CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<CORxRecursoDireito>();
    }
}
