//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Core.INF.DB
{
    public  partial class CORxDireiro
    {
        #region XDefault

        public class XDefault
        {
            public static Guid EC1EFFEA1CCF45FEBE30B91CE86673A8 = new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8");
            public static Guid DD926A0424894BEFBABA87F63000B330 = new Guid("DD926A04-2489-4BEF-BABA-87F63000B330");
            public static Guid _79457E9E99484C3C8605D810AF504E4C = new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C");
            public static Guid _00000000000000000000000000000000 = new Guid("00000000-0000-0000-0000-000000000000");
            public static Guid _4B7D2E6B55004156B6F83A42C3A9B398 = new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398");
            private static Dictionary<Guid, CORxDireiro> _SeedData = new Dictionary<Guid, CORxDireiro>()
            {
                [new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8")] = new CORxDireiro { CORxDireiroID = new Guid("EC1EFFEA-1CCF-45FE-BE30-B91CE86673A8"), Direito = @"Inserir", SYSxEstadoID = (Int16)0 },
                [new Guid("DD926A04-2489-4BEF-BABA-87F63000B330")] = new CORxDireiro { CORxDireiroID = new Guid("DD926A04-2489-4BEF-BABA-87F63000B330"), Direito = @"Inativar", SYSxEstadoID = (Int16)0 },
                [new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C")] = new CORxDireiro { CORxDireiroID = new Guid("79457E9E-9948-4C3C-8605-D810AF504E4C"), Direito = @"Deletar", SYSxEstadoID = (Int16)0 },
                [new Guid("00000000-0000-0000-0000-000000000000")] = new CORxDireiro { CORxDireiroID = new Guid("00000000-0000-0000-0000-000000000000"), Direito = @"Visualizar", SYSxEstadoID = (Int16)0 },
                [new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398")] = new CORxDireiro { CORxDireiroID = new Guid("4B7D2E6B-5500-4156-B6F8-3A42C3A9B398"), Direito = @"Alterar", SYSxEstadoID = (Int16)0 }
            };

            public static CORxDireiro[] SeedData => _SeedData.Values.ToArray();

        }
        #endregion XDefault
        [Display(Name = "Direito")]
        [Required()]
        public Guid? CORxDireiroID {get; set;} = Guid.Empty;

        [MaxLength(45)]
        [Required()]
        public String Direito {get; set;}

        [Display(Name = "Estado")]
        [Required()]
        public Int16 SYSxEstadoID {get; set;}

        public CORxEstado CORxEstado {get; set;}
        public List<CORxPerfilDireiro> CORxPerfilDireiro {get; set;} = new List<CORxPerfilDireiro>();
        public List<CORxRecursoDireito> CORxRecursoDireito {get; set;} = new List<CORxRecursoDireito>();
    }
}
