//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;

namespace STX.App.Core.INF.Perfil
{
    [Route("STXAppCoreINF/Perfil/Perfil")]
    [ApiController]
    public class PerfilController : XController
    {
        public PerfilController(IPerfilService pService, ILogger<XController> pLogger)
               :base(pLogger)
        {
            _Service = pService;
        }

        private readonly IPerfilService _Service;

        [HttpPost("GetByPK")]
        public PerfilDataSet GetByPK([FromBody] PerfilRequest pRequest)
        {
            var dataset = _Service.Select(pRequest, true);
            return dataset;
        }

        [HttpPost("Flush")]
        public IActionResult Flush([FromBody] PerfilDataSet pDataSet)
        {
            _Service.Flush(pDataSet);
            return new OkResult();
        }
    }
}