//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;

namespace TFX.App.Core.TST
{
    public class TFXAppCoreTSTModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
        }
    }
}