//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXCoreAccessUsuariosUsuariosAtivosMDL } from './UsuariosAtivos.Model';
import { STXCoreAccessUsuariosUsuariosAtivosRLE } from './UsuariosAtivos.Service.Rule';

export namespace STXCoreAccessUsuariosUsuariosAtivosSVC
{

    @Injectable()
    export class UsuariosAtivosService extends XService
    {

        static CID = 'BD4A5722-A0F8-42BB-9BA0-264DFD0F525D';

        static Create(http: HttpClient): UsuariosAtivosService
        {
            return new UsuariosAtivosService(http, null);
        }

        constructor(private http: HttpClient, public Rule: STXCoreAccessUsuariosUsuariosAtivosRLE.UsuariosAtivosRule)
        {
            super();
        }

        override DoSearch(pCallback: XMethod<XDataSet<XDataTuple>>)
        {
            let filter = new STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosFilter();
            this.Search(filter, pCallback);
        }

        Search(pFilter: STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosFilter, pCallback: XMethod<STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet>)
        {
            let ret = this.http.post(`${environment.apiBaseURI}/STXCoreAccess/Usuarios/UsuariosAtivos/Search`, pFilter);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        GetByPK(pRequest: STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosRequest, pCallback: XMethod<STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXCoreAccess/Usuarios/UsuariosAtivos/GetByPK`, pRequest);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        New(pCallback: XMethod<STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet>)
        {
            let ndst = new STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet();
            ndst.New();
            pCallback.apply(ndst, [ndst]);
        }

        Save(pDataSet: STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosDataSet, pCallback: XMethod<boolean>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXCoreAccess/Usuarios/UsuariosAtivos/Flush`, pDataSet);
            ret.subscribe({
                next: (isok) =>
                {
                    pCallback.apply(isok, [isok]);
                }
            });
        }
    }
}
