//<auto-generated/>
import { XRule } from '../../material/Component/XComponent';
export namespace STXCoreAccessUsuariosUsuariosAtivosMDL
{

    export class UsuariosAtivosRule extends XRule<UsuariosAtivosDataSet>
    {
    }

    export class UsuariosAtivosTuple extends XDataTuple
    {
        constructor(pSource?: any)
        {
            super();
            this.Assign(pSource);
        }

            override GetPKValue(): any { return this.TAFxUsuarioID.Value; }

        TAFxUsuarioID = new XDataField(XFieldState.Empty, () => 'XGuid', () => '');
        Login = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        Ativo = new XDataField(XFieldState.Empty, () => 'XInt16', () => '');

    }

    export class UsuariosAtivosDataSet extends XDataSet<UsuariosAtivosTuple>
    {
        constructor(pDataSet?: UsuariosAtivosDataSet)
        {
            super();
            if (pDataSet != null)
                this.Assign(UsuariosAtivosTuple, pDataSet);
            for (var i = 0; i < this.Tuples.length; i++)
            {
                let ttpl = this.Tuples[i];
                let stpl = pDataSet.Tuples[i];
            }
        }
    }

    export class UsuariosAtivosRequest extends XRequest
    {
        TAFxUsuarioID?: string;
    }

    export class UsuariosAtivosFilter extends XFilter
    {
        Ativo = new XDataField(XFieldState.Empty, () => 'XInt16', () => '');
        Login = new XDataField(XFieldState.Empty, () => 'XString', () => '');
    }
}
