//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXCoreAccessUsuariosUsuariosAtivosMDL } from './UsuariosAtivos.Model';

export namespace STXCoreAccessUsuariosUsuariosAtivosRLE
{

    @Injectable()
    export class UsuariosAtivosRule extends STXCoreAccessUsuariosUsuariosAtivosMDL.UsuariosAtivosRule
    {
    }
}
