//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using STX.Core.Model;
using STX.Core.Interfaces;
using STX.Access.Model;
using STX.Core.Services;

namespace STX.App.Core.INF.Usuario
{

    public class UsuarioApp : XSAMApplication
    {
        public static class FRMUsuario
        {
            public static readonly Guid ID = new Guid("2060E23A-EE1B-43AD-99E3-CAC64DF688C8");
            public static readonly XFRMField Nome = new XFRMField(new Guid("18C0F5BC-F431-4C82-9E00-47AF374A1193"), "Nome");
            public static readonly XFRMField Login = new XFRMField(new Guid("351967F6-F262-42A1-A6DD-98DC0AB3367D"), "Login");
            public static readonly XFRMField CORxEstadoID = new XFRMField(new Guid("D721336F-2A70-41CC-81B9-2400EC529953"), "CORxEstadoID");
        }
        public UsuarioApp()
        {
            Title = "Cadastro de Usuários";
            Module = "STX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745");
            Ordem = 1;
        }
        public static readonly Guid ID = new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745");
    }
}