//<auto-generated/>
using System.Collections.Generic;
using System.Text;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;
using STX.Core.Exceptions;
using STX.Core.Services;

namespace STX.Core.Automateds.Configuracoes
{
    public class ConfiguracaoJobRule : BaseConfiguracaoJobRule
    {
        public ConfiguracaoJobRule(XService pService)
               :base(pService)
        {
        }

		protected override void AfterSelect(List<ConfiguracaoJobTuple> pTuples)
		{
		
		}

		protected override void BeforeFlush(List<ConfiguracaoJobTuple> pTuples)
		{
			throw new XError("lksjdklsjdlkjskl");
			//pTuples[0].Dados.Value = Encoding.UTF8.GetBytes("{\"RabbitMQHost\":\"tootega.com.br:45054\",\"RabbitMQSenha\":\"@SenhaDaMaria21\",\"RabbitMQUsuario\":\"Maria\",\"Interval\":500,\"ID\":\"841380A0-BAB4-4C30-B780-899BA326E1FB\"}");
		}
	}
}
