//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;

namespace STX.Core.Automateds.Configuracoes
{
    [Route("STXCore/Automateds/Configuracoes/ConfiguracaoJob")]
    [ApiController]
    public class ConfiguracaoJobController : XController
    {
        public ConfiguracaoJobController(IConfiguracaoJobService pService, ILogger<XController> pLogger)
               :base(pLogger)
        {
            _Service = pService;
        }

        private readonly IConfiguracaoJobService _Service;

        [HttpPost("GetByPK")]
        public ConfiguracaoJobDataSet GetByPK([FromBody] ConfiguracaoJobRequest pRequest)
        {
            var dataset = _Service.Select(pRequest, true);
            return dataset;
        }

        [HttpPost("Flush")]
        public IActionResult Flush([FromBody] ConfiguracaoJobDataSet pDataSet)
        {
            _Service.Flush(pDataSet);
            return new OkResult();
        }
    }
}