//<auto-generated/>
import { Component, ElementRef } from '@angular/core';
import { STXAppCoreINFPerfilPerfilSVC } from './Perfil.Service';
import { STXAppCoreINFPerfilPerfilMDL } from './Perfil.Model';

import { XEditorComponent } from '../../material/Component/XEditorComponent';

    @Component({
    templateUrl: './Perfil.Edit.Component.html'
        })
    export class PerfilEditorComponent extends XEditorComponent
    {

        static CID = '657A9FA0-53A7-493F-90BB-9286D46C50C6';

        constructor(pElmRef: ElementRef, private _PerfilService: STXAppCoreINFPerfilPerfilSVC.PerfilService)
        {
             super(pElmRef);
            this.ID = '657A9FA0-53A7-493F-90BB-9286D46C50C6';
        }

        override DataSet: STXAppCoreINFPerfilPerfilMDL.PerfilDataSet

        GetByPK(pPKValue: any)
        {
            let request = new STXAppCoreINFPerfilPerfilMDL.PerfilRequest();
            request.CORxPerfilID = pPKValue;
            this._PerfilService.GetByPK(request, (dst) => {this.DataSet = dst});
        }
    }

