//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPerfilPerfilMDL } from './Perfil.Model';

export namespace STXAppCoreINFPerfilPerfilRLE
{

    @Injectable()
    export class PerfilRule extends STXAppCoreINFPerfilPerfilMDL.PerfilRule
    {
    }
}
