//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPerfilPerfilMDL } from './Perfil.Model';
import { STXAppCoreINFPerfilPerfilRLE } from './Perfil.Service.Rule';

export namespace STXAppCoreINFPerfilPerfilSVC
{

    @Injectable()
    export class PerfilService extends XService
    {
        static CID = 'C622AE73-BC2E-4E1B-9AFE-CF9579A69E1F';
        constructor(private http: HttpClient, public Rule: STXAppCoreINFPerfilPerfilRLE.PerfilRule)
        {
            super();
        }



        GetByPK(pRequest: STXAppCoreINFPerfilPerfilMDL.PerfilRequest, pCallback: XMethod<STXAppCoreINFPerfilPerfilMDL.PerfilDataSet>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/Perfil/Perfil/getbypk`, pRequest);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXAppCoreINFPerfilPerfilMDL.PerfilDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        Save(pDataSet: STXAppCoreINFPerfilPerfilMDL.PerfilDataSet, pCallback: XMethod<boolean>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/Perfil/Perfil`, pDataSet);
            ret.subscribe({
                next: (isok) =>
                {
                    pCallback.apply(isok, [isok]);
                }
            });
        }
    }
}
