//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPerfilPerfilDireitoMDL } from './PerfilDireito.Model';
import { STXAppCoreINFPerfilPerfilDireitoRLE } from './PerfilDireito.Service.Rule';

export namespace STXAppCoreINFPerfilPerfilDireitoSVC
{

    @Injectable()
    export class PerfilDireitoService extends XService
    {
        static CID = 'D653C667-14D8-4FEC-8B91-931A9F9AF041';
        constructor(private http: HttpClient, public Rule: STXAppCoreINFPerfilPerfilDireitoRLE.PerfilDireitoRule)
        {
            super();
        }



        GetByPK(pRequest: STXAppCoreINFPerfilPerfilDireitoMDL.PerfilDireitoRequest, pCallback: XMethod<STXAppCoreINFPerfilPerfilDireitoMDL.PerfilDireitoDataSet>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/Perfil/PerfilDireito/getbypk`, pRequest);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXAppCoreINFPerfilPerfilDireitoMDL.PerfilDireitoDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        Save(pDataSet: STXAppCoreINFPerfilPerfilDireitoMDL.PerfilDireitoDataSet, pCallback: XMethod<boolean>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/Perfil/PerfilDireito`, pDataSet);
            ret.subscribe({
                next: (isok) =>
                {
                    pCallback.apply(isok, [isok]);
                }
            });
        }
    }
}
