//<auto-generated/>
using System;
using TFX.Core.Model;

namespace TFX.App.Core.INF.Usuario
{
    public class Usuario : XSAMApplication
    {
        public Usuario()
        {
            Title = "Cadastro de Usuários";
            Module = "TFX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745");
            Ordem = 1;
        }
    }
}
