//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;

namespace TFX.Core.Automateds.Jobs
{
    public class JobRule : BaseJobRule
    {
        public JobRule(XService pService)
               :base(pService)
        {
        }
    }
}