//<auto-generated/>
using System;
using TFX.Core.Model;

namespace TFX.App.Core.INF.Perfil
{
    public class Perfil : XSAMApplication
    {
        public Perfil()
        {
            Title = "Perfil de Acesso";
            Module = "TFX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0");
            Ordem = 1;
        }
    }
}
