//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using STX.Core.Model;
using STX.Core.Interfaces;
using STX.Access;
using STX.Access.Model;
using STX.Core.Services;
using STX.App.Core.INF.Perfil;

namespace STX.App.Core.TST.Perfil
{

    public class PerfilSAMInsercoesTestSAM : XWebScrapTest<PerfilApp, PerfilSAMInsercoesTestSVCRule, PerfilTuple>
    {
        public PerfilSAMInsercoesTestSAM(XWebScrapSetup pSetup)
            : base(pSetup)
        {
        }

        private PerfilTuple _Tuple;

        [Theory, ClassData(typeof(PerfilSAMInsercoesTestSVC.Data))]
        public void Flush(Int32 pIndex, PerfilTuple pTuple)
        {
            _Tuple = pTuple;
            PerfilSAMInsercoesTestSVCRule rule = CreateRule();
            XLog.AddLog("Iníciando Test de ");
            Setup.Browser.AddLoadEvent(PageLoaded);
            Setup.Browser.GotoAsync("http://localhost:4200");
            rule.BeforeExecute(pIndex, pTuple);
            Setup.Wait();
        }

        private async void PageLoaded()
        {
            PerfilSVC.XTuple r = Model.DataSet[CurrentPlay];
            ExecuteCommand(CurrentPlay, new XSendTextCommand(PerfilSAMInsercoesTestSAM.PerfilFRM.Fields.Nome, r.Nome)); // Nome do Perfil
//        No forms defined for field
        }
    }
}