//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;

namespace STX.Core.Access.Usuarios
{
    public class UsuariosAtivosRule : UsuariosAtivosService.XRule
    {
        public UsuariosAtivosRule(UsuariosAtivosService pService)
               :base(pService)
        {
        }

    }
}