//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;
using STX.Core.Services;

namespace STX.Core.Access.Usuarios
{
    public class UsuariosAtivosRule : BaseUsuariosAtivosRule
    {
        public UsuariosAtivosRule(XService pService)
               :base(pService)
        {
        }

    }
}
