//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;

namespace TFX.Core.Access.Usuarios
{
    public class UsuariosAtivosRule : BaseUsuariosAtivosRule
    {
        public UsuariosAtivosRule(XService pService)
               :base(pService)
        {
        }
    }
}
