//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using STX.Core.Model;
using STX.Core.Interfaces;
using STX.Core;
using STX.Core.Services;

namespace STX.App.Core.INF.Perfil
{

    public class PerfilApp : XSAMApplication
    {
        public static class FRMPerfil
        {
            public static readonly Guid ID = new Guid("0A5822F2-881E-45FE-9E74-0688F30888F4");
            public static readonly XFRMField Nome = new XFRMField(new Guid("4DD2A909-C89A-4342-A2D8-AD335048CFDB"), "Nome");
            public static readonly XFRMField CORxPerfilID = new XFRMField(new Guid("6519FC74-9210-4C30-B4C5-7CBBBE7009D7"), "CORxPerfilID");
        }
        public PerfilApp()
        {
            Title = "Perfil de Acesso";
            Module = "STX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0");
            Ordem = 1;
        }
        public static readonly Guid ID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0");
    }
}