// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STX.Core.Automateds;

#nullable disable

namespace STX.Core.Automateds.Migrations
{
    [DbContext(typeof(STXCoreContext))]
    partial class STXCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STX.Core.Automateds.CORxJob", b =>
                {
                    b.Property<Guid?>("CORxJobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CORxJobID")
                        .HasName("PK_CORxJob");

                    b.ToTable("CORxJob", (string)null);
                });

            modelBuilder.Entity("STX.Core.Automateds.CORxJobConfiguracao", b =>
                {
                    b.Property<Guid?>("CORxJobConfiguracaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxJobID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Dados")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("CORxJobConfiguracaoID")
                        .HasName("PK_CORxJobConfiguracao");

                    b.HasIndex("CORxJobID")
                        .HasDatabaseName("IX_F6BABB8A554A4A2CAA9BD16B8A9148F5");

                    b.ToTable("CORxJobConfiguracao", (string)null);
                });

            modelBuilder.Entity("STX.Core.Automateds.CORxJobConfiguracao", b =>
                {
                    b.HasOne("STX.Core.Automateds.CORxJob", "CORxJob")
                        .WithMany("CORxJobConfiguracao")
                        .HasForeignKey("CORxJobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_F6BABB8A554A4A2CAA9BD16B8A9148F5");

                    b.Navigation("CORxJob");
                });

            modelBuilder.Entity("STX.Core.Automateds.CORxJob", b =>
                {
                    b.Navigation("CORxJobConfiguracao");
                });
#pragma warning restore 612, 618
        }
    }
}
