//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.Core.Automateds
{
    public class CORxJobConfiguracao
    {
        [Display(Name = "Configurações")]
        [Required()]
        public Guid? CORxJobConfiguracaoID {get; set;}

        [Display(Name = "Job")]
        [Required()]
        public Guid CORxJobID {get; set;}

        [Required()]
        public Byte[] Dados {get; set;}

        public CORxJob CORxJob {get; set;}
    }
}
