//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;
using TFX.Core.Access.Usuarios;

namespace TFX.Core.Access
{
    public class TFXCoreAccessModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
            pServices.AddTransient<IUsuariosAtivosService, UsuariosAtivosService>();
            pServices.AddDbContext<UsuariosAtivosService.DBContext>();
        }
    }
}