//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;

namespace TFX.App.Core.INF.Usuario
{
    [Route("TFXAppCoreINF/Usuario/Usuario")]
    [ApiController]
    public class UsuarioController : XController
    {
        public UsuarioController(IUsuarioService pService, ILogger<XController> pLogger)
               :base(pLogger)
        {
            _Service = pService;
        }

        private readonly IUsuarioService _Service;

        [HttpPost("GetByPK")]
        public UsuarioDataSet GetByPK([FromBody] UsuarioRequest pRequest)
        {
            var dataset = _Service.Select(pRequest, null, true);
            return dataset;
        }

        [HttpPost("Flush")]
        public IActionResult Flush([FromBody] UsuarioDataSet pDataSet)
        {
            _Service.Flush(pDataSet);
            return new OkResult();
        }

        [HttpPost("Search")]
        public UsuarioDataSet Search([FromBody] UsuarioFilter pFilter)
        {
            var dataset = _Service.Select(null, pFilter, false);
            return dataset;
        }
    }
}