// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STX.App.Core.INF.DB;

#nullable disable

namespace STX.App.Core.INF.DB.Migrations
{
    [DbContext(typeof(STXAppCoreINFContext))]
    [Migration("20240626125835_SQLServerIni")]
    partial class SQLServerIni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxDireiro", b =>
                {
                    b.Property<Guid?>("CORxDireiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direito")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("CORxDireiroID")
                        .HasName("PK_CORxDireiro");

                    b.ToTable("CORxDireiro", (string)null);

                    b.HasData(
                        new
                        {
                            CORxDireiroID = new Guid("ec1effea-1ccf-45fe-be30-b91ce86673a8"),
                            Direito = "Inserir"
                        },
                        new
                        {
                            CORxDireiroID = new Guid("dd926a04-2489-4bef-baba-87f63000b330"),
                            Direito = "Inativar"
                        },
                        new
                        {
                            CORxDireiroID = new Guid("79457e9e-9948-4c3c-8605-d810af504e4c"),
                            Direito = "Deletar"
                        },
                        new
                        {
                            CORxDireiroID = new Guid("04b3a66c-c0f0-4f99-9864-08403baa71be"),
                            Direito = "Visualizar"
                        },
                        new
                        {
                            CORxDireiroID = new Guid("4b7d2e6b-5500-4156-b6f8-3a42c3a9b398"),
                            Direito = "Alterar"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxEstado", b =>
                {
                    b.Property<short>("CORxEstadoID")
                        .HasColumnType("smallint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CORxEstadoID")
                        .HasName("PK_CORxEstado");

                    b.ToTable("CORxEstado", (string)null);

                    b.HasData(
                        new
                        {
                            CORxEstadoID = (short)0,
                            Estado = "Inativo"
                        },
                        new
                        {
                            CORxEstadoID = (short)1,
                            Estado = "Ativo"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxMenuItem", b =>
                {
                    b.Property<Guid?>("CORxMenuItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxMenuItemPaiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CORxMenuItemID")
                        .HasName("PK_CORxMenuItem");

                    b.HasIndex("CORxMenuItemPaiID")
                        .HasDatabaseName("IX_089E501462F24B4CB82B6401E77C1CD9");

                    b.ToTable("CORxMenuItem", (string)null);

                    b.HasData(
                        new
                        {
                            CORxMenuItemID = new Guid("620df346-cc9d-4333-b57e-8b5454e5617c"),
                            CORxMenuItemPaiID = new Guid("2de8c87d-4e4a-4e57-a567-a6f5acb92e05"),
                            Icone = "bi bi-alipay",
                            Nome = "Item da POC"
                        },
                        new
                        {
                            CORxMenuItemID = new Guid("00000000-0000-0000-0000-000000000000"),
                            CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icone = "NI",
                            Nome = "NI"
                        },
                        new
                        {
                            CORxMenuItemID = new Guid("2de8c87d-4e4a-4e57-a567-a6f5acb92e05"),
                            CORxMenuItemPaiID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icone = "bi bi-alipay",
                            Nome = "POC"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfil", b =>
                {
                    b.Property<Guid?>("CORxPerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("CORxPerfilID")
                        .HasName("PK_CORxPerfil");

                    b.ToTable("CORxPerfil", (string)null);

                    b.HasData(
                        new
                        {
                            CORxPerfilID = new Guid("67bd4f5d-4fb2-40a0-84c1-bd75ae669dd1"),
                            Nome = "Administrador"
                        },
                        new
                        {
                            CORxPerfilID = new Guid("9a0b3913-4ca5-46d6-8161-3cfd80ca7ad2"),
                            Nome = "Vendedor"
                        },
                        new
                        {
                            CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "NA"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfilDireiro", b =>
                {
                    b.Property<Guid?>("CORxPerfilDireiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPerfilID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxRecursoDireitoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxPerfilDireiroID")
                        .HasName("PK_CORxPerfilDireiro");

                    b.HasIndex("CORxPerfilID")
                        .HasDatabaseName("IX_DB2EF4796E004A85B4BBEC4BAFB60B61");

                    b.HasIndex("CORxRecursoDireitoID")
                        .HasDatabaseName("IX_43FA8B4D965A44388AB05C4C95CD4120");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_C81CBAAB358F4F87B64A7EFD7808B76B");

                    b.HasIndex("CORxPerfilID", "CORxPerfilDireiroID")
                        .IsUnique()
                        .HasDatabaseName("IX_8EA98120_28B4_458C_946B_E9B0000C518D");

                    b.ToTable("CORxPerfilDireiro", (string)null);

                    b.HasData(
                        new
                        {
                            CORxPerfilDireiroID = new Guid("3c1fc583-ae51-471d-b9e6-f32e1e4fed46"),
                            CORxPerfilID = new Guid("67bd4f5d-4fb2-40a0-84c1-bd75ae669dd1"),
                            CORxRecursoDireitoID = new Guid("bffdec08-20e6-473e-8e78-767fbc07498c"),
                            SYSxEstadoID = (short)1
                        },
                        new
                        {
                            CORxPerfilDireiroID = new Guid("10853d40-58f1-4b93-874d-b49a61f8e486"),
                            CORxPerfilID = new Guid("67bd4f5d-4fb2-40a0-84c1-bd75ae669dd1"),
                            CORxRecursoDireitoID = new Guid("6187f500-b6ad-46e8-94e6-f2751c9358b1"),
                            SYSxEstadoID = (short)1
                        },
                        new
                        {
                            CORxPerfilDireiroID = new Guid("726ff2aa-9caa-46b9-9c1c-4422f23203b6"),
                            CORxPerfilID = new Guid("67bd4f5d-4fb2-40a0-84c1-bd75ae669dd1"),
                            CORxRecursoDireitoID = new Guid("789c7f93-9343-42fd-9970-e99bd4d03de3"),
                            SYSxEstadoID = (short)1
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPessoa", b =>
                {
                    b.Property<Guid?>("CORxPessoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("CORxPessoaID")
                        .HasName("PK_CORxPessoa");

                    b.ToTable("CORxPessoa", (string)null);

                    b.HasData(
                        new
                        {
                            CORxPessoaID = new Guid("8e330979-c053-45e6-a1ed-5fa20d03e18f"),
                            Nome = "Administrador"
                        },
                        new
                        {
                            CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "NA"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecurso", b =>
                {
                    b.Property<Guid?>("CORxRecursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxMenuItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CORxRecursoID")
                        .HasName("PK_CORxRecurso");

                    b.HasIndex("CORxMenuItemID")
                        .HasDatabaseName("IX_DD2B2F889A7341ACB8763984D8EB927F");

                    b.ToTable("CORxRecurso", (string)null);

                    b.HasData(
                        new
                        {
                            CORxRecursoID = new Guid("99df499e-844f-47ee-aee6-c6462b18a3e0"),
                            CORxMenuItemID = new Guid("2de8c87d-4e4a-4e57-a567-a6f5acb92e05"),
                            Nome = "Perfil de Acesso"
                        },
                        new
                        {
                            CORxRecursoID = new Guid("e678fe01-3fe3-45e6-a3ff-1aad064d3745"),
                            CORxMenuItemID = new Guid("2de8c87d-4e4a-4e57-a567-a6f5acb92e05"),
                            Nome = "Usuário"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecursoDireito", b =>
                {
                    b.Property<Guid?>("CORxRecursoDireitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxDireiroID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxRecursoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxRecursoDireitoID")
                        .HasName("PK_CORxRecursoDireito");

                    b.HasIndex("CORxDireiroID")
                        .HasDatabaseName("IX_FEBE37E773C04510917C09AA991BA695");

                    b.HasIndex("CORxRecursoID")
                        .HasDatabaseName("IX_63A2BC55DE5B48F9B50DB67210086133");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_662808A15CC541869E041EB76DBF81F2");

                    b.HasIndex("CORxDireiroID", "CORxRecursoID")
                        .IsUnique()
                        .HasDatabaseName("IX_29FB7252_4D26_4B87_85F7_DED1FB18AC29");

                    b.ToTable("CORxRecursoDireito", (string)null);

                    b.HasData(
                        new
                        {
                            CORxRecursoDireitoID = new Guid("6187f500-b6ad-46e8-94e6-f2751c9358b1"),
                            CORxDireiroID = new Guid("ec1effea-1ccf-45fe-be30-b91ce86673a8"),
                            CORxRecursoID = new Guid("99df499e-844f-47ee-aee6-c6462b18a3e0"),
                            SYSxEstadoID = (short)1
                        },
                        new
                        {
                            CORxRecursoDireitoID = new Guid("bffdec08-20e6-473e-8e78-767fbc07498c"),
                            CORxDireiroID = new Guid("79457e9e-9948-4c3c-8605-d810af504e4c"),
                            CORxRecursoID = new Guid("99df499e-844f-47ee-aee6-c6462b18a3e0"),
                            SYSxEstadoID = (short)1
                        },
                        new
                        {
                            CORxRecursoDireitoID = new Guid("789c7f93-9343-42fd-9970-e99bd4d03de3"),
                            CORxDireiroID = new Guid("04b3a66c-c0f0-4f99-9864-08403baa71be"),
                            CORxRecursoID = new Guid("99df499e-844f-47ee-aee6-c6462b18a3e0"),
                            SYSxEstadoID = (short)1
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxTenat", b =>
                {
                    b.Property<Guid?>("CORxTenatID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CORxPessoaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CORxTenatID")
                        .HasName("PK_CORxTenat");

                    b.HasIndex("CORxPessoaID");

                    b.HasIndex("CORxTenatID")
                        .HasDatabaseName("IX_7763556284A541589093B4B776F38198");

                    b.ToTable("CORxTenat", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.Property<Guid?>("CORxUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPerfilID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPessoaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CORxUsuarioID")
                        .HasName("PK_CORxUsuario");

                    b.HasIndex("CORxPerfilID")
                        .HasDatabaseName("IX_5EADF4BC787543D68D639FEBDDD377A1");

                    b.HasIndex("CORxPessoaID")
                        .HasDatabaseName("IX_C9471B8665C04206AC2FBA967434C37A");

                    b.HasIndex("CORxUsuarioID")
                        .HasDatabaseName("IX_74C786F513D84B83B262F901573BCE27");

                    b.ToTable("CORxUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            CORxUsuarioID = new Guid("00000000-0000-0000-0000-000000000000"),
                            CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000"),
                            CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CORxUsuarioID = new Guid("eba53c9e-c110-4ca3-96fd-420dc75207b1"),
                            CORxPerfilID = new Guid("00000000-0000-0000-0000-000000000000"),
                            CORxPessoaID = new Guid("8e330979-c053-45e6-a1ed-5fa20d03e18f")
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuarioPerfil", b =>
                {
                    b.Property<Guid?>("CORxUsuarioPerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPerfilID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxUsuarioPerfilID")
                        .HasName("PK_CORxUsuarioPerfil");

                    b.HasIndex("CORxPerfilID")
                        .HasDatabaseName("IX_A1545961E23B49F9A6C3797816459BA6");

                    b.HasIndex("CORxUsuarioID")
                        .HasDatabaseName("IX_277FC3C02F294E4BB98861248A39AF3E");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_DF6B83584AFE4750963FA1CCDD988B7A");

                    b.HasIndex("CORxUsuarioID", "CORxPerfilID")
                        .IsUnique()
                        .HasDatabaseName("IX_41898A44_44C6_4757_BCD7_45183345E9D3");

                    b.ToTable("CORxUsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("STX.Core.Access.DB.TAFxUsuario", b =>
                {
                    b.Property<Guid?>("TAFxUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CORxEstadoID")
                        .HasColumnType("smallint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TAFxUsuarioID")
                        .HasName("PK_TAFxUsuario");

                    b.ToTable("TAFxUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            TAFxUsuarioID = new Guid("eba53c9e-c110-4ca3-96fd-420dc75207b1"),
                            CORxEstadoID = (short)1,
                            Login = "Administrador"
                        },
                        new
                        {
                            TAFxUsuarioID = new Guid("00000000-0000-0000-0000-000000000000"),
                            CORxEstadoID = (short)0,
                            Login = "NA"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxMenuItem", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxMenuItem", "ItemPai")
                        .WithMany("ItensFilhos")
                        .HasForeignKey("CORxMenuItemPaiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_089E501462F24B4CB82B6401E77C1CD9");

                    b.Navigation("ItemPai");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfilDireiro", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPerfil", "CORxPerfil")
                        .WithMany("CORxPerfilDireiro")
                        .HasForeignKey("CORxPerfilID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DB2EF4796E004A85B4BBEC4BAFB60B61");

                    b.HasOne("STX.App.Core.INF.DB.CORxRecursoDireito", "CORxRecursoDireito")
                        .WithMany("CORxPerfilDireiro")
                        .HasForeignKey("CORxRecursoDireitoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_43FA8B4D965A44388AB05C4C95CD4120");

                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxPerfilDireiro")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_C81CBAAB358F4F87B64A7EFD7808B76B");

                    b.Navigation("CORxEstado");

                    b.Navigation("CORxPerfil");

                    b.Navigation("CORxRecursoDireito");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecurso", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxMenuItem", "CORxMenuItem")
                        .WithMany("CORxRecurso")
                        .HasForeignKey("CORxMenuItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DD2B2F889A7341ACB8763984D8EB927F");

                    b.Navigation("CORxMenuItem");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecursoDireito", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxDireiro", "CORxDireiro")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("CORxDireiroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FEBE37E773C04510917C09AA991BA695");

                    b.HasOne("STX.App.Core.INF.DB.CORxRecurso", "CORxRecurso")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("CORxRecursoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_63A2BC55DE5B48F9B50DB67210086133");

                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_662808A15CC541869E041EB76DBF81F2");

                    b.Navigation("CORxDireiro");

                    b.Navigation("CORxEstado");

                    b.Navigation("CORxRecurso");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxTenat", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPessoa", null)
                        .WithMany("CORxTenat")
                        .HasForeignKey("CORxPessoaID");

                    b.HasOne("STX.App.Core.INF.DB.CORxPessoa", "CORxPessoa")
                        .WithMany()
                        .HasForeignKey("CORxTenatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_7763556284A541589093B4B776F38198");

                    b.Navigation("CORxPessoa");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPerfil", "CORxPerfil")
                        .WithMany("CORxUsuario")
                        .HasForeignKey("CORxPerfilID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_5EADF4BC787543D68D639FEBDDD377A1");

                    b.HasOne("STX.App.Core.INF.DB.CORxPessoa", "CORxPessoa")
                        .WithMany("CORxUsuario")
                        .HasForeignKey("CORxPessoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_C9471B8665C04206AC2FBA967434C37A");

                    b.HasOne("STX.Core.Access.DB.TAFxUsuario", "TAFxUsuario")
                        .WithMany()
                        .HasForeignKey("CORxUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_74C786F513D84B83B262F901573BCE27");

                    b.Navigation("CORxPerfil");

                    b.Navigation("CORxPessoa");

                    b.Navigation("TAFxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuarioPerfil", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPerfil", "CORxPerfil")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("CORxPerfilID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_A1545961E23B49F9A6C3797816459BA6");

                    b.HasOne("STX.App.Core.INF.DB.CORxUsuario", "CORxUsuario")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("CORxUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_277FC3C02F294E4BB98861248A39AF3E");

                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DF6B83584AFE4750963FA1CCDD988B7A");

                    b.Navigation("CORxEstado");

                    b.Navigation("CORxPerfil");

                    b.Navigation("CORxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxDireiro", b =>
                {
                    b.Navigation("CORxRecursoDireito");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxEstado", b =>
                {
                    b.Navigation("CORxPerfilDireiro");

                    b.Navigation("CORxRecursoDireito");

                    b.Navigation("CORxUsuarioPerfil");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxMenuItem", b =>
                {
                    b.Navigation("CORxRecurso");

                    b.Navigation("ItensFilhos");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfil", b =>
                {
                    b.Navigation("CORxPerfilDireiro");

                    b.Navigation("CORxUsuario");

                    b.Navigation("CORxUsuarioPerfil");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPessoa", b =>
                {
                    b.Navigation("CORxTenat");

                    b.Navigation("CORxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecurso", b =>
                {
                    b.Navigation("CORxRecursoDireito");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecursoDireito", b =>
                {
                    b.Navigation("CORxPerfilDireiro");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.Navigation("CORxUsuarioPerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
