// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STX.App.Core.INF.DB;

#nullable disable

namespace STX.App.Core.INF.DB.Migrations
{
    [DbContext(typeof(STXAppCoreINFContext))]
    [Migration("20240611203617_SQLServerIni")]
    partial class SQLServerIni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxDireiro", b =>
                {
                    b.Property<Guid?>("CORxDireiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direito")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxDireiroID")
                        .HasName("PK_CORxDireiro");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_2C9B6EBB73B54370A430415BCD452E6E");

                    b.ToTable("CORxDireiro", (string)null);

                    b.HasData(
                        new
                        {
                            CORxDireiroID = new Guid("ec1effea-1ccf-45fe-be30-b91ce86673a8"),
                            Direito = "Inserir",
                            SYSxEstadoID = (short)0
                        },
                        new
                        {
                            CORxDireiroID = new Guid("dd926a04-2489-4bef-baba-87f63000b330"),
                            Direito = "Inativar",
                            SYSxEstadoID = (short)0
                        },
                        new
                        {
                            CORxDireiroID = new Guid("79457e9e-9948-4c3c-8605-d810af504e4c"),
                            Direito = "Deletar",
                            SYSxEstadoID = (short)0
                        },
                        new
                        {
                            CORxDireiroID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Direito = "Visualizar",
                            SYSxEstadoID = (short)0
                        },
                        new
                        {
                            CORxDireiroID = new Guid("4b7d2e6b-5500-4156-b6f8-3a42c3a9b398"),
                            Direito = "Alterar",
                            SYSxEstadoID = (short)0
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxEstado", b =>
                {
                    b.Property<short>("CORxEstadoID")
                        .HasColumnType("smallint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CORxEstadoID")
                        .HasName("PK_CORxEstado");

                    b.ToTable("CORxEstado", (string)null);

                    b.HasData(
                        new
                        {
                            CORxEstadoID = (short)0,
                            Estado = "Inativo"
                        },
                        new
                        {
                            CORxEstadoID = (short)1,
                            Estado = "Ativo"
                        });
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfil", b =>
                {
                    b.Property<Guid?>("CORxPerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("CORxPerfilID")
                        .HasName("PK_CORxPerfil");

                    b.ToTable("CORxPerfil", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfilDireiro", b =>
                {
                    b.Property<Guid?>("CORxPerfilDireiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxDireiroID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPerfilID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CORxPerfilDireiroID")
                        .HasName("PK_CORxPerfilDireiro");

                    b.HasIndex("CORxDireiroID")
                        .HasDatabaseName("IX_C6414CDFD26A410BA65457F3CD38FE4A");

                    b.HasIndex("CORxPerfilID")
                        .HasDatabaseName("IX_DB2EF4796E004A85B4BBEC4BAFB60B61");

                    b.HasIndex("CORxPerfilID", "CORxDireiroID")
                        .IsUnique()
                        .HasDatabaseName("IX_8EA98120_28B4_458C_946B_E9B0000C518D");

                    b.ToTable("CORxPerfilDireiro", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPessoa", b =>
                {
                    b.Property<Guid?>("CORxPessoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("CORxPessoaID")
                        .HasName("PK_CORxPessoa");

                    b.ToTable("CORxPessoa", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecurso", b =>
                {
                    b.Property<Guid?>("CORxRecursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CORxRecursoID")
                        .HasName("PK_CORxRecurso");

                    b.ToTable("CORxRecurso", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecursoDireito", b =>
                {
                    b.Property<Guid?>("CORxRecursoDireitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxDireiroID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxRecursoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxRecursoDireitoID")
                        .HasName("PK_CORxRecursoDireito");

                    b.HasIndex("CORxDireiroID")
                        .HasDatabaseName("IX_FEBE37E773C04510917C09AA991BA695");

                    b.HasIndex("CORxRecursoID")
                        .HasDatabaseName("IX_63A2BC55DE5B48F9B50DB67210086133");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_662808A15CC541869E041EB76DBF81F2");

                    b.HasIndex("CORxDireiroID", "CORxRecursoID")
                        .IsUnique()
                        .HasDatabaseName("IX_29FB7252_4D26_4B87_85F7_DED1FB18AC29");

                    b.ToTable("CORxRecursoDireito", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.Property<Guid?>("CORxUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPessoaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TAFxUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CORxUsuarioID")
                        .HasName("PK_CORxUsuario");

                    b.HasIndex("CORxPessoaID")
                        .HasDatabaseName("IX_C9471B8665C04206AC2FBA967434C37A");

                    b.HasIndex("CORxUsuarioID")
                        .HasDatabaseName("IX_74C786F513D84B83B262F901573BCE27");

                    b.HasIndex("TAFxUsuarioID");

                    b.ToTable("CORxUsuario", (string)null);
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuarioPerfil", b =>
                {
                    b.Property<Guid?>("CORxUsuarioPerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxPerfilID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CORxUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SYSxEstadoID")
                        .HasColumnType("smallint");

                    b.HasKey("CORxUsuarioPerfilID")
                        .HasName("PK_CORxUsuarioPerfil");

                    b.HasIndex("CORxPerfilID")
                        .HasDatabaseName("IX_A1545961E23B49F9A6C3797816459BA6");

                    b.HasIndex("CORxUsuarioID")
                        .HasDatabaseName("IX_277FC3C02F294E4BB98861248A39AF3E");

                    b.HasIndex("SYSxEstadoID")
                        .HasDatabaseName("IX_DF6B83584AFE4750963FA1CCDD988B7A");

                    b.HasIndex("CORxUsuarioID", "CORxPerfilID")
                        .IsUnique()
                        .HasDatabaseName("IX_41898A44_44C6_4757_BCD7_45183345E9D3");

                    b.ToTable("CORxUsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("STX.Core.Access.DB.TAFxUsuario", b =>
                {
                    b.Property<Guid?>("TAFxUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TAFxUsuarioID");

                    b.ToTable("TAFxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxDireiro", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxDireiro")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_2C9B6EBB73B54370A430415BCD452E6E");

                    b.Navigation("CORxEstado");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfilDireiro", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxDireiro", "CORxDireiro")
                        .WithMany("CORxPerfilDireiro")
                        .HasForeignKey("CORxDireiroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_C6414CDFD26A410BA65457F3CD38FE4A");

                    b.HasOne("STX.App.Core.INF.DB.CORxPerfil", "CORxPerfil")
                        .WithMany("CORxPerfilDireiro")
                        .HasForeignKey("CORxPerfilID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DB2EF4796E004A85B4BBEC4BAFB60B61");

                    b.Navigation("CORxDireiro");

                    b.Navigation("CORxPerfil");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecursoDireito", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxDireiro", "CORxDireiro")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("CORxDireiroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FEBE37E773C04510917C09AA991BA695");

                    b.HasOne("STX.App.Core.INF.DB.CORxRecurso", "CORxRecurso")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("CORxRecursoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_63A2BC55DE5B48F9B50DB67210086133");

                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxRecursoDireito")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_662808A15CC541869E041EB76DBF81F2");

                    b.Navigation("CORxDireiro");

                    b.Navigation("CORxEstado");

                    b.Navigation("CORxRecurso");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPessoa", "CORxPessoa")
                        .WithMany("CORxUsuario")
                        .HasForeignKey("CORxPessoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_C9471B8665C04206AC2FBA967434C37A");

                    b.HasOne("STX.Core.Access.DB.TAFxUsuario", null)
                        .WithMany()
                        .HasForeignKey("CORxUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_74C786F513D84B83B262F901573BCE27");

                    b.HasOne("STX.Core.Access.DB.TAFxUsuario", "TAFxUsuario")
                        .WithMany()
                        .HasForeignKey("TAFxUsuarioID");

                    b.Navigation("CORxPessoa");

                    b.Navigation("TAFxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuarioPerfil", b =>
                {
                    b.HasOne("STX.App.Core.INF.DB.CORxPerfil", "CORxPerfil")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("CORxPerfilID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_A1545961E23B49F9A6C3797816459BA6");

                    b.HasOne("STX.App.Core.INF.DB.CORxUsuario", "CORxUsuario")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("CORxUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_277FC3C02F294E4BB98861248A39AF3E");

                    b.HasOne("STX.App.Core.INF.DB.CORxEstado", "CORxEstado")
                        .WithMany("CORxUsuarioPerfil")
                        .HasForeignKey("SYSxEstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DF6B83584AFE4750963FA1CCDD988B7A");

                    b.Navigation("CORxEstado");

                    b.Navigation("CORxPerfil");

                    b.Navigation("CORxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxDireiro", b =>
                {
                    b.Navigation("CORxPerfilDireiro");

                    b.Navigation("CORxRecursoDireito");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxEstado", b =>
                {
                    b.Navigation("CORxDireiro");

                    b.Navigation("CORxRecursoDireito");

                    b.Navigation("CORxUsuarioPerfil");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPerfil", b =>
                {
                    b.Navigation("CORxPerfilDireiro");

                    b.Navigation("CORxUsuarioPerfil");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxPessoa", b =>
                {
                    b.Navigation("CORxUsuario");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxRecurso", b =>
                {
                    b.Navigation("CORxRecursoDireito");
                });

            modelBuilder.Entity("STX.App.Core.INF.DB.CORxUsuario", b =>
                {
                    b.Navigation("CORxUsuarioPerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
