//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;

namespace TFX.App.Core.INF.Usuario
{
    public class UsuarioRule : BaseUsuarioRule
    {
        public UsuarioRule(XService pService)
               :base(pService)
        {
        }
    }
}