//Usuario => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Usuario\Usuario.Component.css
//Usuario => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Usuario\Usuario.Component.html
//Usuario => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Usuario\Usuario.Component.ts
//Usuario => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Usuario\Usuario.Edit.Component.ts
//Usuario => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Usuario\Usuario.Edit.Component.html
//<auto-generated/>
using System;
using STX.Core.Model;

namespace STX.App.Core.INF.Usuario
{
    public class Usuario : XSAMApplication
    {
        public Usuario()
        {
            Title = "Cadastro de Usuários";
            Module = "STX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("E678FE01-3FE3-45E6-A3FF-1AAD064D3745");
            Ordem = 1;
        }
    }
}