//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;

namespace TFX.App.Journal.INF.DB
{
    public class JNLxAcao : XEntity
    {
        public class XDefault
        {
            private static Dictionary<Int16, JNLxAcao> _SeedData = new Dictionary<Int16, JNLxAcao>()
            {
                [(Int16)2] = new JNLxAcao { JNLxAcaoID = (Int16)2, Acao = @"Alteração" },
                [(Int16)3] = new JNLxAcao { JNLxAcaoID = (Int16)3, Acao = @"Deleção" },
                [(Int16)1] = new JNLxAcao { JNLxAcaoID = (Int16)1, Acao = @"Inserção" }
            };

            public static JNLxAcao[] SeedData => _SeedData.Values.ToArray();

        }
        [Display(Name = "Ação")]
        [MaxLength(15)]
        [Required()]
        public String Acao {get; set;}

        public Boolean IsPKEmpty => Object.Equals(JNLxAcaoID, typeof(Int16).GetDefault());
        [Display(Name = "Ação")]
        [Required()]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Int16 JNLxAcaoID {get; set;}

        public List<JNLxRevisao> JNLxRevisao {get; set;} = new List<JNLxRevisao>();
    }
}
