//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;
using TFX.Core.Access.DB;
using TFX.App.Core.INF.DB;

namespace TFX.App.Journal.INF.DB
{
    public class JNLxRevisao : XEntity
    {
        [MaxLength(100)]
        [Required()]
        public String App {get; set;}

        [Display(Name = "Tenat")]
        [Required()]
        public Guid CORxTenatID {get; set;}

        [Required()]
        public DateTime Data {get; set;}

        [MaxLength(50)]
        [Required()]
        public String Host {get; set;}

        [Display(Name = "Ação")]
        [Required()]
        public Int16 JNLxAcaoID {get; set;}

        public Boolean IsPKEmpty => Object.Equals(JNLxRevisaoID, typeof(Int64).GetDefault());
        [Display(Name = "Revisão")]
        [Required()]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Int64 JNLxRevisaoID {get; set;}

        [Display(Name = "Tabela")]
        [Required()]
        public Guid JNLxTabelaID {get; set;}

        [Display(Name = "Usuários")]
        [Required()]
        public Guid TAFxUsuarioID {get; set;}

        [Display(Name = "Transação")]
        [Required()]
        public Guid Transacao {get; set;}

        public JNLxTabela JNLxTabela {get; set;}
        public TAFxUsuario TAFxUsuario {get; set;}
        public CORxTenat CORxTenat {get; set;}
        public JNLxAcao JNLxAcao {get; set;}
    }
}
