//<auto-generated/>
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;
using STX.Core.Services;

namespace STX.App.Core.INF.PessoaFisica
{
    public class PessoaFisicaRule : BasePessoaFisicaRule
    {
        public PessoaFisicaRule(XService pService)
               :base(pService)
        {
        }

        protected override void AfterSelect(List<PessoaFisicaTuple> pTuples)
        {
            base.AfterSelect(pTuples);
        }
    }
}
