//<auto-generated/>
using System;
using TFX.Core.Reflections;
using TFX.Core.Model.DIC;

namespace STX.App.Core.INF
{
    [XRegister(typeof(STXAppCoreINF), sCID)]
    [XDASESource(@"D:\Tootega\Source\Access-POC\App\Modules\STX.App.Core.INF\STX.App.Core.INF.csproj", @"D:\Tootega\Source\Access-POC\App\Modules\STX.App.Core.INF\STX.App.Core.INF.dsmdl")]
    public class STXAppCoreINF : XModule
    {
        public const String sCID = "565065C6-AE16-4A13-A7BF-D6910086D4F2";
        public static Guid gCID = new Guid(sCID);
        public STXAppCoreINF()
        {
            ID = new Guid("565065C6-AE16-4A13-A7BF-D6910086D4F2");
            Name = "STX.App.Core.INF";
            Title = "";
            Groups = new Guid[]{  };
        }
    }
}