//<auto-generated/>
using System;
using System.Linq;
using TFX.Core;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TFX.Core.Lzma;
using TFX.App.Core.INF.DB;

namespace TFX.App.Journal.INF.DB
{
    public class JNLxTabela : XEntity
    {
        [Display(Name = "Nome Chave Primária")]
        [MaxLength(128)]
        [Required()]
        public String CampoPK {get; set;}

        public Boolean IsPKEmpty => Object.Equals(JNLxTabelaID, typeof(Guid).GetDefault());
        [Display(Name = "Tabela")]
        [Required()]
        public Guid? JNLxTabelaID {get; set;}

        [Display(Name = "Estado")]
        [Required()]
        public Int16 SYSxEstadoID {get; set;}

        [MaxLength(128)]
        [Required()]
        public String Tabela {get; set;}

        [Display(Name = "Tipo Chave")]
        [MaxLength(128)]
        [Required()]
        public String TipoPK {get; set;}

        public CORxEstado CORxEstado {get; set;}
        public List<JNLxCampo> JNLxCampo {get; set;} = new List<JNLxCampo>();
        public List<JNLxPesquisa> JNLxPesquisa {get; set;} = new List<JNLxPesquisa>();
        public List<JNLxRevisao> JNLxRevisao {get; set;} = new List<JNLxRevisao>();
    }
}
