//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.App.Journal.INF.DB
{
    public class JNLxPesquisa
    {
        [Display(Name = "Consulta ao Jornal")]
        [Required()]
        public Byte[] Consulta {get; set;}

        [Display(Name = "Consulta Tabela de Dados")]
        [Required()]
        public Byte[] ConsultaDado {get; set;}

        [Display(Name = "Pesquisa")]
        [Required()]
        public Guid? JNLxPesquisaID {get; set;} = Guid.Empty;

        [Display(Name = "Tabela")]
        [Required()]
        public Guid JNLxTabelaID {get; set;}

        [MaxLength(80)]
        [Required()]
        public String Nome {get; set;}

        public JNLxTabela JNLxTabela {get; set;}
    }
}
