//<auto-generated/>
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using STX.Core;

namespace STX.App.Journal.INF.DB
{
    public class STXAppJournalINFContext : XDBContext
    {

        public STXAppJournalINFContext(DbContextOptions pOptions)
          : base(pOptions)
        {
        
        }

        public STXAppJournalINFContext(DbContextOptions<STXAppJournalINFContext> pOptions)
          : base(pOptions)
        {
        
        }

        protected override void OnModelCreating(ModelBuilder pBuilder)
        {
        }
    }
}