//<auto-generated/>
import { Component, ElementRef } from '@angular/core';
import { STXAppCoreINFUsuarioUsuarioSVC } from './Usuario.Service';
import { STXAppCoreINFUsuarioUsuarioMDL } from './Usuario.Model';

import { XSearchComponent } from 'material/Component/XSearchComponent';

    @Component({
        templateUrl: './Usuario.Component.html',
        styleUrls: ['./Usuario.Component.css']
    })
    export class UsuarioComponent extends XSearchComponent<STXAppCoreINFUsuarioUsuarioMDL.UsuarioTuple, STXAppCoreINFUsuarioUsuarioMDL.UsuarioDataSet>
    {
        static CID = 'E678FE01-3FE3-45E6-A3FF-1AAD064D3745';

        constructor(pElmRef: ElementRef, private _UsuarioService: STXAppCoreINFUsuarioUsuarioSVC.UsuarioService)
        {
            super(pElmRef);
            this.ID = 'E678FE01-3FE3-45E6-A3FF-1AAD064D3745';
            this.EditorID = '98F19B33-0739-4748-AD89-5FCCE6074048';
            this.Filter = new STXAppCoreINFUsuarioUsuarioMDL.UsuarioFilter();
        }

        override Rights = [XDefaultRights.Alterar, XDefaultRights.Configurar, XDefaultRights.Inativar, XDefaultRights.Incluir, XDefaultRights.Restaurar, XDefaultRights.Visualizar];
        override Filter = new STXAppCoreINFUsuarioUsuarioMDL.UsuarioFilter();

        override  DoLoadByPK(pPKValue: any, pCallBack: XMethod<STXAppCoreINFUsuarioUsuarioMDL.UsuarioDataSet>)
        {
            let request = new STXAppCoreINFUsuarioUsuarioMDL.UsuarioRequest();
            request.CORxUsuarioID = pPKValue;
            this._UsuarioService.GetByPK(request, pCallBack);
        }

        override DoSave(pDataSet: STXAppCoreINFUsuarioUsuarioMDL.UsuarioDataSet, pCallBack: XMethod<boolean>)
        {
            this._UsuarioService.Save(pDataSet, pCallBack);
        }

        Search(pEvent: any)
        {
            this._UsuarioService.Search(this.Filter, (dst) => {this.SetDataSet(dst)});
        }
    }

