//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFUsuarioUsuarioMDL } from './Usuario.Model';

export namespace STXAppCoreINFUsuarioUsuarioRLE
{

    @Injectable()
    export class UsuarioRule extends STXAppCoreINFUsuarioUsuarioMDL.UsuarioRule
    {
    }
}
