//PessoaFisica => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\PessoaFisica\PessoaFisica.Component.css
//PessoaFisica => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\PessoaFisica\PessoaFisica.Component.html
//PessoaFisica => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\PessoaFisica\PessoaFisica.Component.ts
//PessoaFisica => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\PessoaFisica\PessoaFisica.Edit.Component.ts
//PessoaFisica => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\PessoaFisica\PessoaFisica.Edit.Component.html
//<auto-generated/>
using System;
using STX.Core.Model;

namespace STX.App.Core.INF.PessoaFisica
{
    public class PessoaFisica : XSAMApplication
    {
        public PessoaFisica()
        {
            Title = "Pessoa Física";
            Module = "STX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("14DAAEA4-EE5B-4AEF-B527-5383C0BD185D");
            Ordem = 1;
        }
    }
}