//<auto-generated/>
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using STX.Core;

namespace STX.Core.Access.DB
{
    public class STXCoreAccessContext : XDBContext
    {

        public STXCoreAccessContext(DbContextOptions<STXCoreAccessContext> pOptions)
          : base(pOptions)
        {
        
        }

        public DbSet<TAFxUsuario> TAFxUsuario{get; set;}
        protected override void OnModelCreating(ModelBuilder pBuilder)
        {
            ConfigureTAFxUsuario(pBuilder);
        }

        private void ConfigureTAFxUsuario(ModelBuilder pBuilder)
        {
            pBuilder.Entity<TAFxUsuario>(ett =>
            {
                ett.HasKey(e => e.TAFxUsuarioID).HasName("PK_TAFxUsuario");
                
                ett.Property(d => d.TAFxUsuarioID).HasColumnType(GetDBType("Guid", 0, 0));
                ett.Property(d => d.Login).HasColumnType(GetDBType("String", 0, 0));
                ett.Property(d => d.CORxEstadoID).HasColumnType(GetDBType("Int16", 0, 0));
                ett.ToTable("TAFxUsuario");
                ett.HasData(STX.Core.Access.DB.TAFxUsuario.XDefault.SeedData);
            });
        }
    }
}