//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.Core.Access.DB
{
    public class TAFxUsuario
    {
        [Required()]
        public Int16 Ativo {get; set;}

        [Required()]
        public String Login {get; set;}

        [Display(Name = "Usuários")]
        [Required()]
        public Guid? TAFxUsuarioID {get; set;} = Guid.Empty;

    }
}
