//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.Core.Access.DB
{
    public class TAFxUsuario
    {
        public class XDefault
        {
            private static Dictionary<Guid, TAFxUsuario> _SeedData = new Dictionary<Guid, TAFxUsuario>()
            {
                [new Guid("EBA53C9E-C110-4CA3-96FD-420DC75207B1")] = new TAFxUsuario { TAFxUsuarioID = new Guid("EBA53C9E-C110-4CA3-96FD-420DC75207B1"), Login = @"Administrador", CORxEstadoID = (Int16)1 },
                [new Guid("00000000-0000-0000-0000-000000000000")] = new TAFxUsuario { TAFxUsuarioID = new Guid("00000000-0000-0000-0000-000000000000"), Login = @"NA", CORxEstadoID = (Int16)0 }
            };

            public static TAFxUsuario[] SeedData => _SeedData.Values.ToArray();

        }
        [Display(Name = "Ativo")]
        [Required()]
        public Int16 CORxEstadoID {get; set;}

        [Required()]
        public String Login {get; set;}

        [Display(Name = "Usuários")]
        [Required()]
        public Guid? TAFxUsuarioID {get; set;}

    }
}
