//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STX.Core.Access.DB
{
    public  static class TAFModel
    {

        public static class TAFxUsuario
        {
            public const string sNA = @"NA";
            public static Guid NA = new Guid("00000000-0000-0000-0000-000000000000");
        }
    }
}