//<auto-generated/>
using System;
using System.Collections.Generic;
using STX.Access;
using STX.App.Core.TST.Usuario;
using STX.App.Core.INF.Usuario;

namespace STX.App.Core.TST.Usuario
{
    public class UsuarioSAMsdsdsdTestTest : XTest<UsuarioTestRule, UsuarioTuple>
    {
        public abstract class Rule :  XTestRule<UsuarioTuple>
        {
        }

        [Theory, ClassData(typeof(Data))]
        public void Flush(Int32 pIndex, UsuarioTuple pTuple)
        {
        }

        [Theory, ClassData(typeof(Data))]
        public void Select(Int32 pIndex, UsuarioFilter pFilter)
        {
        }

        public override void Run()
        {
        }

        public class Data : XTestData<UsuarioTuple>
        {
        public Data()
            {
                UsuarioTuple datatpl;
                datatpl = new UsuarioTuple();
                Data.Add(new object[] {0, datatpl});
                datatpl.Login = @"NA";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("00000000-0000-0000-0000-000000000000");
                datatpl.CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000");
                datatpl.Nome = @"NA";
                datatpl = new UsuarioTuple();
                Data.Add(new object[] {1, datatpl});
                datatpl.Login = @"Joana";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("91FB8C8C-2050-4407-A729-3023C5CA1A20");
                datatpl.CORxPessoaID = new Guid("00000000-0000-0000-0000-000000000000");
                datatpl.Nome = @"NA";
                datatpl = new UsuarioTuple();
                Data.Add(new object[] {2, datatpl});
                datatpl.Login = @"Administrador";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("EBA53C9E-C110-4CA3-96FD-420DC75207B1");
                datatpl.CORxPessoaID = new Guid("8E330979-C053-45E6-A1ED-5FA20D03E18F");
                datatpl.Nome = @"Administrador";
                datatpl = new UsuarioTuple();
                Data.Add(new object[] {3, datatpl});
                datatpl.Login = @"Ana Maria";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("9B202BA0-4C4A-42DF-BD88-D771A8AA5D29");
                datatpl.CORxPessoaID = new Guid("7635A0E4-1672-4E92-AE10-BD54D789C1FD");
                datatpl.Nome = @"Maria Ana";
            }

        }
    }
}