//<auto-generated/>
using System;
using System.Collections.Generic;
using STX.Access;
using STX.Core.Model;
using STX.Core.Services;
using STX.App.Core.INF.Perfil;
using STX.Core.Test.Factories;
using STX.Core.Test.Interfaces;
using Microsoft.Playwright;
using STX.App.Core.INF.Usuario;
using System.Runtime.CompilerServices;

namespace STX.App.Core.TST.Usuario
{
    public class UsuarioSAMWebTest : XWebScrapTest<UsuarioApp,UsuarioSAMWebTestRule, UsuarioTuple>
    {
        private UsuarioTuple _Tuple;

        public UsuarioSAMWebTest(XWebScrapSetup pSetup)
            : base(pSetup)
        {
        }

        public abstract class Rule : XTestRule<UsuarioTuple>
        {
        }


        protected override void DoDisposeSetup(XIWSBrowser pBrowser)
        {
        }

        [Theory, ClassData(typeof(Data))]
        public void Flush(Int32 pIndex, UsuarioTuple pTuple)
        {
            _Tuple = pTuple;
            XLog.AddLog("START " + pTuple.Nome + " " + pTuple.CORxUsuarioID.Value);
            Setup.Browser.AddLoadEvent(PageLoaded);
            Setup.Browser.GotoAsync("http://localhost:4200");
            //UsuarioSAMWebTestRule rule = CreateRule();
            //rule.BeforeExecute(pIndex, pTuple);
            //PerfilDataSet dst = new PerfilDataSet();
            //dst.Tuples.Add(pTuple);


            //PerfilDataSet dstret = persvc.GetByPK(new PerfilRequest { CORxPerfilID = pTuple.CORxPerfilID }, true);
            //foreach (var tpl in dstret.Tuples)
            //    rule.AfterExecute(pIndex, tpl, pTuple);
            Setup.Wait();
        }

        private async void PageLoaded()
        {
            await Setup.Browser.CurrentPage.GetById("POC").ClickToVisible();
            await Setup.Browser.CurrentPage.GetById(App.MenuID).ClickToVisible();
            await Setup.Browser.CurrentPage.GetById(App.BtnSearchID).ClickAsync();
            if (Setup.Browser.CurrentPage.CheckElement("tr", new XAtt("id", _Tuple.CORxUsuarioID.Value.AsString())) == true)
            {
                await Setup.Browser.CurrentPage.GetById(App.BtnNewID).ClickAsync();
                if (Setup.Browser.CurrentPage.CheckElement("div", new XAtt("id", UsuarioApp.FRMUsuario.ID.AsString())) == true)
                {
                    await Setup.Browser.CurrentPage.GetById(UsuarioApp.FRMUsuario.Nome.ID).Focus();
                    await Setup.Browser.CurrentPage.HumanTypingAsync(_Tuple.Nome);
                    await Setup.Browser.CurrentPage.GetById(UsuarioApp.FRMUsuario.Login.ID).Focus();
                    await Setup.Browser.CurrentPage.HumanTypingAsync(_Tuple.Login);
                    await Setup.Browser.CurrentPage.GetById(UsuarioApp.FRMUsuario.CORxEstadoID.ID).Focus();
                    await Setup.Browser.CurrentPage.HumanTypingAsync(_Tuple.CORxEstadoID.Value.AsString());
                }
                Setup.Continue();
            }
        }

        public class Data : XTestData<UsuarioTuple>
        {
            public Data()
            {
                UsuarioTuple datatpl;
                datatpl = new UsuarioTuple();
                datatpl.State = XTupleState.Added;
                Data.Add(new object[] { 0, datatpl });
                datatpl.Login = @"helena.farias@sittax.com.br";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("FCBF7664-331D-4023-A650-D9CA6E7E0FB0");
                datatpl.CORxPessoaID = new Guid("500FCF2C-82C0-42ED-A18D-3ECAA7C8C5A6");
                datatpl.Nome = @"Helena Farias Oliveira";
                datatpl = new UsuarioTuple();
                datatpl.State = XTupleState.Added;
                Data.Add(new object[] { 1, datatpl });
                datatpl.Login = @"solange.moraes@sittax.com.br";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("3CA6191A-A7CB-47BF-A560-9EAFC23E2623");
                datatpl.CORxPessoaID = new Guid("676355C4-1087-4328-91C4-CD696291E539");
                datatpl.Nome = @"Solange Moraies Alves";
                datatpl = new UsuarioTuple();
                datatpl.State = XTupleState.Added;
                Data.Add(new object[] { 2, datatpl });
                datatpl.Login = @"ana.carla@sittax.com.br";
                datatpl.CORxEstadoID = (Int16)1;
                datatpl.CORxUsuarioID = new Guid("4F411508-1744-4D9F-8635-015600B4E058");
                datatpl.CORxPessoaID = new Guid("18C5877D-9F81-4CD2-962C-12BEE7EBC239");
                datatpl.Nome = @"Ana Carla Alencar";
            }

        }
    }
}
