//<auto-generated/>
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using STX.Core.Model;
using STX.Core.Interfaces;
using STX.Access;
using STX.Access.Model;
using STX.Core.Services;
using STX.App.Core.INF.Usuario;

namespace STX.App.Core.TST.Usuario
{

    public class UsuarioSAMInsercoesTestSAM : XWebScrapTest<UsuarioApp, UsuarioSAMInsercoesTestSVCRule, UsuarioTuple>
    {
        public UsuarioSAMInsercoesTestSAM(XWebScrapSetup pSetup)
            : base(pSetup)
        {
        }

        private UsuarioTuple _Tuple;

        [Theory, ClassData(typeof(UsuarioSAMInsercoesTestSVC.Data))]
        public void Flush(Int32 pIndex, UsuarioTuple pTuple)
        {
            _Tuple = pTuple;
            UsuarioSAMInsercoesTestSVCRule rule = CreateRule();
            XLog.AddLog("Iníciando Test de ");
            Setup.Browser.AddLoadEvent(PageLoaded);
            Setup.Browser.GotoAsync("http://localhost:4200");
            rule.BeforeExecute(pIndex, pTuple);
            Setup.Wait();
        }

        private async void PageLoaded()
        {
            UsuarioSVC.XTuple r = Model.DataSet[CurrentPlay];
            ExecuteCommand(CurrentPlay, new XSendTextCommand(UsuarioSAMInsercoesTestSAM.UsuarioFRM.Fields.Nome, r.Nome)); // Nome
            ExecuteCommand(CurrentPlay, new XSendTextCommand(UsuarioSAMInsercoesTestSAM.UsuarioFRM.Fields.Login, r.Login)); // Login
            ExecuteCommand(CurrentPlay, new XSendDecimalCommand(UsuarioSAMInsercoesTestSAM.UsuarioFRM.Fields.CORxEstadoID, r.CORxEstadoID)); // Ativo
        }
    }
}