//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;
using STX.Core.Services;
using STX.App.Core.INF.Usuario;

namespace STX.App.Core.TST.Usuario
{
    public class UsuarioSAMsdsdsdTestRule : UsuarioSAMsdsdsdTestTest.Rule
    {
        public override void AfterExecute(Int32 pIndex, UsuarioTuple pTuple)
        {
        }

        public override void BeforeExecute(Int32 pIndex, UsuarioTuple pTuple)
        {
        }
    }
}
