//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;

namespace TFX.App.Core.INF.Perfil
{
    [Route("TFXAppCoreINF/Perfil/PerfilDireito")]
    [ApiController]
    public class PerfilDireitoController : XController
    {
        public PerfilDireitoController(IPerfilDireitoService pService, ILogger<XController> pLogger)
               :base(pLogger)
        {
            _Service = pService;
        }

        private readonly IPerfilDireitoService _Service;

        [HttpPost("GetByPK")]
        public PerfilDireitoDataSet GetByPK([FromBody] PerfilDireitoRequest pRequest)
        {
            var dataset = _Service.Select(pRequest, true);
            return dataset;
        }

        [HttpPost("Flush")]
        public IActionResult Flush([FromBody] PerfilDireitoDataSet pDataSet)
        {
            _Service.Flush(pDataSet);
            return new OkResult();
        }
    }
}
