//<auto-generated/>
using System;
using System.Linq;
using STX.Core.Model;
using Microsoft.Extensions.DependencyInjection;

namespace STX.App.Journal.INF
{
    public class STXAppJournalINFModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
        }
    }
}