//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;

namespace TFX.App.Journal.INF
{
    public class TFXAppJournalINFModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
        }
    }
}