//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TFX.Core.Controllers;
using TFX.Core.Services;

namespace TFX.App.Core.INF.Perfil
{
    public class PerfilRule : BasePerfilRule
    {
        public PerfilRule(XService pService)
               :base(pService)
        {
        }
    }
}
