//Perfil => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Perfil\Perfil.Component.css
//Perfil => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Perfil\Perfil.Component.html
//Perfil => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Perfil\Perfil.Component.ts
//Perfil => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Perfil\Perfil.Edit.Component.ts
//Perfil => D:\Tootega\Source\Access-POC\App\Launchers\WebUI\src\STX-App-Core-INF\Perfil\Perfil.Edit.Component.html
//<auto-generated/>
using System;
using STX.Core.Model;

namespace STX.App.Core.INF.Perfil
{
    public class Perfil : XSAMApplication
    {
        public Perfil()
        {
            Title = "Perfil de Acesso";
            Module = "STX.App.Core.INF";
            Icon = "";
            MenuID = new Guid("99DF499E-844F-47EE-AEE6-C6462B18A3E0");
            Ordem = 1;
        }
    }
}