//<auto-generated/>
import { Component, ElementRef } from '@angular/core';
import { STXAppCoreINFPessoaFisicaPessoaFisicaSVC } from './PessoaFisica.Service';
import { STXAppCoreINFPessoaFisicaPessoaFisicaMDL } from './PessoaFisica.Model';

import { XSearchComponent } from 'material/Component/XSearchComponent';

    @Component({
        templateUrl: './PessoaFisica.Component.html',
        styleUrls: ['./PessoaFisica.Component.css']
    })
    export class PessoaFisicaComponent extends XSearchComponent<STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaTuple, STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet>
    {
        static CID = '14DAAEA4-EE5B-4AEF-B527-5383C0BD185D';

        constructor(pElmRef: ElementRef, private _PessoaFisicaService: STXAppCoreINFPessoaFisicaPessoaFisicaSVC.PessoaFisicaService)
        {
            super(pElmRef);
            this.ID = '14DAAEA4-EE5B-4AEF-B527-5383C0BD185D';
            this.EditorID = 'AE0570A7-9532-442E-8E84-140ED261A251';
            this.Filter = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaFilter();
        }

        override Rights = [XDefaultRights.Alterar, XDefaultRights.Configurar, XDefaultRights.Inativar, XDefaultRights.Incluir, XDefaultRights.Restaurar, XDefaultRights.Visualizar];
        override Filter = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaFilter();

        override  DoLoadByPK(pPKValue: any, pCallBack: XMethod<STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet>)
        {
            let request = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaRequest();
            request.CORxPessoaFisicaID = pPKValue;
            this._PessoaFisicaService.GetByPK(request, pCallBack);
        }

        override DoSave(pDataSet: STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet, pCallBack: XMethod<boolean>)
        {
            this._PessoaFisicaService.Save(pDataSet, pCallBack);
        }

        Search(pEvent: any)
        {
            this._PessoaFisicaService.Search(this.Filter, (dst) => {this.SetDataSet(dst)});
        }
    }

