//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPessoaFisicaPessoaFisicaMDL } from './PessoaFisica.Model';
import { STXAppCoreINFPessoaFisicaPessoaFisicaRLE } from './PessoaFisica.Service.Rule';

export namespace STXAppCoreINFPessoaFisicaPessoaFisicaSVC
{

    @Injectable()
    export class PessoaFisicaService extends XService
    {
        static CID = '4ED04271-C2E2-475F-88B7-45D6F1D9E931';
        constructor(private http: HttpClient, public Rule: STXAppCoreINFPessoaFisicaPessoaFisicaRLE.PessoaFisicaRule)
        {
            super();
        }


        override DoSearch(pCallback: XMethod<XDataSet<XDataTuple>>)
        {
            let filter = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaFilter();
            this.Search(filter, pCallback);
        }

        Search(pFilter: STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaFilter, pCallback: XMethod<STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet>)
        {
            let ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/PessoaFisica/PessoaFisica/search`, pFilter);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        GetByPK(pRequest: STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaRequest, pCallback: XMethod<STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/PessoaFisica/PessoaFisica/getbypk`, pRequest);
            ret.subscribe({
                next: (dst) =>
                {
                    let ndst = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet(<any>dst);
                    pCallback.apply(ndst, [ndst]);
                }
            });
        }

        Save(pDataSet: STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet, pCallback: XMethod<boolean>)
        {
            var ret = this.http.post(`${environment.apiBaseURI}/STXAppCoreINF/PessoaFisica/PessoaFisica`, pDataSet);
            ret.subscribe({
                next: (isok) =>
                {
                    pCallback.apply(isok, [isok]);
                }
            });
        }
    }
}
