//<auto-generated/>
import { XRule } from '../../material/Component/XComponent';
export namespace STXAppCoreINFPessoaFisicaPessoaFisicaMDL
{

    export class PessoaFisicaRule extends XRule<PessoaFisicaDataSet>
    {
    }

    export class PessoaFisicaTuple extends XDataTuple
    {
        constructor(pSource?: any)
        {
            super();
            this.Assign(pSource);
        }

            override GetPKValue(): any { return this.CORxPessoaFisiacID.Value; }

        CORxPessoaFisiacID = new XDataField(XFieldState.Empty, () => 'XGuid', () => '');
        Nome = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        Endereco = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        CORxUsuarioID = new XDataField(XFieldState.Empty, () => 'XGuid', () => '');

    }

    export class PessoaFisicaDataSet extends XDataSet<PessoaFisicaTuple>
    {
        constructor(pDataSet?: PessoaFisicaDataSet)
        {
            super();
            if (pDataSet != null)
                this.Assign(PessoaFisicaTuple, pDataSet);
            for (var i = 0; i < this.Tuples.length; i++)
            {
                let ttpl = this.Tuples[i];
                let stpl = pDataSet.Tuples[i];
            }
        }
    }

    export class PessoaFisicaRequest extends XRequest
    {
        CORxPessoaFisiacID?: string;
    }

    export class PessoaFisicaFilter extends XFilter
    {
        Endereco = new XDataField(XFieldState.Empty, () => 'XString', () => '');
        Nome = new XDataField(XFieldState.Empty, () => 'XString', () => '');
    }
}
