//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPessoaFisicaPessoaFisicaMDL } from './PessoaFisica.Model';

export namespace STXAppCoreINFPessoaFisicaPessoaFisicaRLE
{

    @Injectable()
    export class PessoaFisicaRule extends STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaRule
    {
    }
}
