//<auto-generated/>
import { Component, ElementRef } from '@angular/core';
import { STXAppCoreINFPessoaFisicaPessoaFisicaSVC } from './PessoaFisica.Service';
import { STXAppCoreINFPessoaFisicaPessoaFisicaMDL } from './PessoaFisica.Model';

import { XEditorComponent } from '../../material/Component/XEditorComponent';

    @Component({
    templateUrl: './PessoaFisica.Edit.Component.html'
        })
    export class PessoaFisicaEditorComponent extends XEditorComponent
    {

        static CID = 'AE0570A7-9532-442E-8E84-140ED261A251';

        constructor(pElmRef: ElementRef, private _PessoaFisicaService: STXAppCoreINFPessoaFisicaPessoaFisicaSVC.PessoaFisicaService)
        {
             super(pElmRef);
            this.ID = 'AE0570A7-9532-442E-8E84-140ED261A251';
        }

        override DataSet: STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaDataSet

        GetByPK(pPKValue: any)
        {
            let request = new STXAppCoreINFPessoaFisicaPessoaFisicaMDL.PessoaFisicaRequest();
            request.CORxPessoaFisiacID = pPKValue;
            this._PessoaFisicaService.GetByPK(request, (dst) => {this.DataSet = dst});
        }
    }

