//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXAppCoreINFPerfilPerfilDireitoMDL } from './PerfilDireito.Model';

export namespace STXAppCoreINFPerfilPerfilDireitoRLE
{

    @Injectable()
    export class PerfilDireitoRule extends STXAppCoreINFPerfilPerfilDireitoMDL.PerfilDireitoRule
    {
    }
}
