//<auto-generated/>
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using STX.Core.Controllers;

namespace STX.App.Core.INF.PessoaFisica
{
    [Route("STXAppCoreINF/PessoaFisica/PessoaFisica")]
    [ApiController]
    public class PessoaFisicaController : XController
    {
        public PessoaFisicaController(IPessoaFisicaService pService, ILogger<XController> pLogger)
               :base(pLogger)
        {
            _Service = pService;
        }

        private readonly IPessoaFisicaService _Service;

        [HttpPost("GetByPK")]
        public PessoaFisicaDataSet GetByPK([FromBody] PessoaFisicaRequest pRequest)
        {
            var dataset = _Service.Select(pRequest, null, true);
            return dataset;
        }

        [HttpPost("Flush")]
        public IActionResult Flush([FromBody] PessoaFisicaDataSet pDataSet)
        {
            _Service.Flush(pDataSet);
            return new OkResult();
        }

        [HttpPost("Search")]
        public PessoaFisicaDataSet Search([FromBody] PessoaFisicaFilter pFilter)
        {
            var dataset = _Service.Select(null, pFilter, false);
            return dataset;
        }
    }
}