//<auto-generated/>
using System;
using TFX.Core.Reflections;
using TFX.Core.Model.DIC;

namespace STX.App.Core.API
{
    [XRegister(typeof(STXAppCoreAPI), sCID)]
    [XDASESource(@"D:\Tootega\Source\Access-POC\App\Modules\STX.App.Core.API\STX.App.Core.API.csproj", @"D:\Tootega\Source\Access-POC\App\Modules\STX.App.Core.API\STX.App.Core.API.dsmdl")]
    public class STXAppCoreAPI : XModule
    {
        public const String sCID = "BB23204D-302F-4889-9B9C-2571FBDF2073";
        public static Guid gCID = new Guid(sCID);
        public STXAppCoreAPI()
        {
            ID = new Guid("BB23204D-302F-4889-9B9C-2571FBDF2073");
            Name = "STX.App.Core.API";
            Title = "";
            Groups = new Guid[]{  };
        }
    }
}