<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Core\TFX.Core\TFX.Core.csproj" />
      <ProjectReference Include="..\TFX.App.Journal.MDL\TFX.App.Journal.MDL.csproj" />
    </ItemGroup>

</Project>
