//<auto-generated/>
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { XService, XRule } from 'material/Component/XComponent';
import { STXCoreAutomatedsConfiguracoesConfiguracaoJobMDL } from './ConfiguracaoJob.Model';

export namespace STXCoreAutomatedsConfiguracoesConfiguracaoJobRLE
{

    @Injectable()
    export class ConfiguracaoJobRule extends STXCoreAutomatedsConfiguracoesConfiguracaoJobMDL.ConfiguracaoJobRule
    {
    }
}
